/**
 * Thumbnail Builder V4 – AAA Premium Gaming Thumbnail
 *
 * Architecture: Frame-first. DALL-E is NOT used.
 * Text is generated by GPT, rendered by Sharp+SVG. Never by AI image models.
 *
 * Flow:
 *  1. Download Bebas Neue → /tmp/glenvex-fonts/ (file path, NOT base64)
 *  2. Extract 20 frames spread through the clip
 *  3. Score frames (brightness + position heuristic)
 *  4. Top 5 → GPT-4o Vision → best frame + CTR + subject bounding box
 *  5. Generate 2-3 word punchline headline (GPT sees chosen frame)
 *  6. Build Variant A: subject upper-left, gaming grade, text bottom
 *  7. Build Variant B: subject upper-left, cinematic grade, letterbox text
 *  8. Build Variant C: subject upper-right, drama grade, text bottom-left
 *  9. Upload all to Supabase Storage
 * 10. DB: DONE + variant URLs + CTR score/reason
 *
 * FONT: Uses file:// path reference (not base64) for librsvg compatibility.
 * FALLBACK: DejaVu Sans Bold → Liberation Sans Bold → Impact → sans-serif
 */

import { spawn } from 'child_process';
import { promisify } from 'util';
import { exec } from 'child_process';
import * as fs from 'fs';
import * as path from 'path';
import OpenAI from 'openai';
import { createClient } from '@supabase/supabase-js';
import { logSystemEvent } from './systemEvents';

const execAsync = promisify(exec);
const STORAGE_BUCKET = process.env.STORAGE_BUCKET ?? 'glenvex-assets';

// ── Config ────────────────────────────────────────────────────────────────────

const FRAME_COUNT       = 20;
const TOP_CANDIDATES    = 5;
const MAX_RETRIES       = 2;
const QUALITY_THRESHOLD = 70;

const YT_W = 1280;
const YT_H = 720;
const TT_W = 1080;
const TT_H = 1920;

// ── Font ──────────────────────────────────────────────────────────────────────

const FONT_DIR  = '/tmp/glenvex-fonts';
const FONT_PATH = path.join(FONT_DIR, 'BebasNeue.ttf');
const FONT_URL  = 'https://github.com/google/fonts/raw/main/ofl/bebasneue/BebasNeue-Regular.ttf';

// Fallback font stack for Railway (Debian/Ubuntu) – tested to exist on most images
const FONT_FALLBACK = "'DejaVu Sans', 'Liberation Sans', Arial, sans-serif";

async function prepareFontPath(): Promise<string | null> {
  try {
    if (!fs.existsSync(FONT_PATH)) {
      fs.mkdirSync(FONT_DIR, { recursive: true });
      const res = await fetch(FONT_URL, { signal: AbortSignal.timeout(15_000) });
      if (!res.ok) { log('FONT_DOWNLOAD_FAILED', `HTTP ${res.status}`); return null; }
      fs.writeFileSync(FONT_PATH, Buffer.from(await res.arrayBuffer()));
      log('FONT_DOWNLOADED', FONT_PATH);
    }
    log('FONT_READY', FONT_PATH);
    return FONT_PATH;
  } catch (e: any) {
    log('FONT_DOWNLOAD_FAILED', e.message?.slice(0, 100));
    return null;
  }
}

// ── Logging ───────────────────────────────────────────────────────────────────

function log(step: string, detail = '') {
  console.log(`[ThumbnailV4] ${step}${detail ? ': ' + detail : ''}`);
}

// ── Frame Extraction ──────────────────────────────────────────────────────────

function spawnFrame(
  videoUrl: string,
  t: number,
  w: number,
  h: number,
  timeoutMs = 14_000
): Promise<Buffer | null> {
  return new Promise(resolve => {
    const proc = spawn('ffmpeg', [
      '-ss', String(Math.max(0.1, t)),
      '-i', videoUrl,
      '-vframes', '1',
      '-f', 'image2',
      '-vcodec', 'mjpeg',
      '-q:v', '2',
      '-vf', `scale=${w}:${h}:force_original_aspect_ratio=decrease,pad=${w}:${h}:(ow-iw)/2:(oh-ih)/2:black,setsar=1`,
      'pipe:1',
    ]);
    const chunks: Buffer[] = [];
    proc.stdout?.on('data', (c: Buffer) => chunks.push(c));
    const tid = setTimeout(() => { try { proc.kill('SIGKILL'); } catch {} resolve(null); }, timeoutMs);
    proc.on('close', (code: number) => {
      clearTimeout(tid);
      resolve(code === 0 && chunks.length > 0 ? Buffer.concat(chunks) : null);
    });
    proc.on('error', () => { clearTimeout(tid); resolve(null); });
  });
}

async function getClipDuration(clipUrl: string): Promise<number> {
  try {
    const { stdout } = await execAsync(
      `ffprobe -v error -show_entries format=duration -of csv=p=0 "${clipUrl}"`,
      { timeout: 10_000 }
    );
    const d = parseFloat(stdout.trim());
    return d > 0 && isFinite(d) ? d : 30;
  } catch { return 30; }
}

interface RawFrame {
  idx: number;
  t: number;
  pct: number;
  buf: Buffer;
}

async function extractCandidateFrames(clipUrl: string, duration: number): Promise<RawFrame[]> {
  const percentages = Array.from({ length: FRAME_COUNT }, (_, i) =>
    5 + (i * 90 / (FRAME_COUNT - 1))
  );
  const timestamps = percentages.map(p => Math.max(0.5, (duration * p) / 100));

  const frames: RawFrame[] = [];
  const BATCH = 4;
  for (let i = 0; i < timestamps.length; i += BATCH) {
    const batch = timestamps.slice(i, i + BATCH);
    const results = await Promise.all(
      batch.map(async (t, j) => {
        const buf = await spawnFrame(clipUrl, t, 640, 360, 12_000);
        return buf ? { idx: i + j, t, pct: percentages[i + j], buf } : null;
      })
    );
    frames.push(...(results.filter(Boolean) as RawFrame[]));
  }
  return frames;
}

// ── Frame Scoring ─────────────────────────────────────────────────────────────

function scoreBrightness(buf: Buffer): number {
  const start = Math.floor(buf.length * 0.3);
  const end   = Math.floor(buf.length * 0.7);
  let sum = 0; let n = 0;
  for (let i = start; i < end; i += 50) { sum += buf[i]; n++; }
  const avg = n > 0 ? sum / n : 128;
  if (avg < 35)  return 0;
  if (avg > 225) return 20;
  if (avg < 65)  return 35;
  return 100;
}

function scorePosition(pct: number): number {
  if (pct < 5 || pct > 95)   return 10;
  if (pct < 12 || pct > 88)  return 50;
  return 100;
}

function scoreFrame(frame: RawFrame): number {
  return Math.round((scoreBrightness(frame.buf) * 0.5) + (scorePosition(frame.pct) * 0.5));
}

// ── Frame Analysis (Vision: per-frame scoring + boring rejection) ─────────────

interface SubjectBox {
  x: number; // 0-1 fraction of image width
  y: number;
  w: number;
  h: number;
}

type SubjectType = 'face' | 'character' | 'action' | 'object' | 'none';

interface FrameAnalysis {
  idx: number;          // 0-based index into the frames array
  actionScore: number;  // 0-100: conflict/reaction/drama quality
  boring: boolean;      // true = reject (standing, overview, no story)
  reason: string;
  subjectBox: SubjectBox | null;
  subjectType: SubjectType;
}

// Kept for internal quality-score compatibility
interface CtrResult {
  selectedIdx: number;
  ctrScore: number;
  reason: string;
  subjectBox: SubjectBox | null;
  subjectType: SubjectType;
}

function parseSubjectBox(d: any): SubjectBox | null {
  if (typeof d?.sx !== 'number' || typeof d?.sw !== 'number') return null;
  return {
    x: Math.max(0, Math.min(0.99, d.sx)),
    y: Math.max(0, Math.min(0.99, d.sy ?? 0)),
    w: Math.max(0.05, Math.min(1 - Math.max(0, d.sx), d.sw)),
    h: Math.max(0.05, Math.min(1 - Math.max(0, d.sy ?? 0), d.sh ?? 0.5)),
  };
}

async function analyzeAllFrames(
  client: OpenAI,
  frames: RawFrame[],
  category: string,
  game: string
): Promise<FrameAnalysis[]> {
  const fallback = (): FrameAnalysis[] => frames.map((_, i) => ({
    idx: i, actionScore: 50, boring: false, reason: '', subjectBox: null, subjectType: 'none' as SubjectType,
  }));

  if (frames.length === 0) return [];
  if (frames.length === 1) return [{ idx: 0, actionScore: 60, boring: false, reason: '', subjectBox: null, subjectType: 'none' }];

  const isGtaRp = category === 'RP_MOMENT'
    || game.toLowerCase().includes('gta')
    || game.toLowerCase().includes('roleplay');

  const rpExtra = isGtaRp
    ? '\nGTA RP PRIORITY (weight heavily): police chase, arrest, weapon drawn, fight, crash, panic, fear, visible character reaction.\nBORING in GTA RP: standing idle, peaceful driving, overview map, conversation without visible conflict/weapon.'
    : '';

  const ctrl = new AbortController();
  const tid = setTimeout(() => ctrl.abort(), 22_000);
  try {
    const res = await client.chat.completions.create({
      model: 'gpt-4o-mini',
      max_tokens: 500,
      temperature: 0,
      messages: [{
        role: 'user',
        content: [
          {
            type: 'text',
            text: `These ${frames.length} frames are from a ${game || 'video game'} clip (${category || 'general'}).
Score EACH frame for thumbnail potential (0-100 action score) and detect the main subject.${rpExtra}
BORING = true if: characters just standing, no visible conflict/reaction/action, static overview shot, nothing interesting.
For each frame give subject bounding box (0.0-1.0 fractions of width/height).
Reply ONLY with valid JSON, no markdown:
{"r":[{"n":1,"a":0-100,"b":true,"why":"brief","sx":0.0,"sy":0.0,"sw":0.5,"sh":0.8,"s":"face|character|action|object|none"},...]}`
          },
          ...frames.map(f => ({
            type: 'image_url' as const,
            image_url: { url: `data:image/jpeg;base64,${f.buf.toString('base64')}`, detail: 'low' as const },
          })),
        ],
      }],
    }, { signal: ctrl.signal } as any);
    clearTimeout(tid);

    const raw = res.choices[0]?.message?.content ?? '';
    // Strip markdown fences if present
    const clean = raw.replace(/^```[a-z]*\n?/i, '').replace(/\n?```$/i, '').trim();
    const m = clean.match(/\{[\s\S]*\}/);
    if (!m) throw new Error('No JSON in response');
    const d = JSON.parse(m[0]);
    if (!Array.isArray(d.r)) throw new Error('Missing r array');

    const results: FrameAnalysis[] = d.r.map((item: any, i: number) => {
      const idx = Math.max(0, Math.min(frames.length - 1, (item.n ?? i + 1) - 1));
      const subjectType: SubjectType = (['face','character','action','object','none'].includes(item.s) ? item.s : 'none');
      return {
        idx,
        actionScore: Math.min(100, Math.max(0, item.a ?? 50)),
        boring: !!item.b,
        reason: String(item.why ?? '').slice(0, 100),
        subjectBox: parseSubjectBox(item),
        subjectType,
      };
    });

    const boringCount = results.filter(r => r.boring).length;
    log('FRAME_ANALYSIS', `${frames.length} frames analyzed, ${boringCount} boring, top=${results.sort((a,b)=>b.actionScore-a.actionScore)[0]?.actionScore}`);
    return results;

  } catch (e: any) {
    clearTimeout(tid);
    log('FRAME_ANALYSIS_FAILED', e.message?.slice(0, 100));
    return fallback();
  }
}

// ── Copy Generation ───────────────────────────────────────────────────────────

async function generateCopy(
  client: OpenAI,
  highlight: any,
  vod: any,
  copies: any[],
  frameB64: string
): Promise<{ headline: string; subheadline: string }> {
  const ytCopy = copies.find((c: any) => c.platform === 'youtube');
  const ttCopy = copies.find((c: any) => c.platform === 'tiktok');

  try {
    const res = await client.chat.completions.create({
      model: 'gpt-4o-mini',
      max_tokens: 120,
      temperature: 0.9,
      messages: [
        {
          role: 'system',
          content: `Du lager PUNCHLINE-tekst til AAA gaming YouTube-thumbnails. Svar KUN med JSON: {"headline":"...","subheadline":"..."}

KRITISKE REGLER:
- headline: MAKS 3 ORD. Ideelt 1-2 ord. Maks 12 tegn. Store bokstaver. Norsk.
- Teksten skal uttrykke FØLELSEN, ikke forklare hva som skjer.
- FEIL: "SPILLER GTA MED POLITIJAKT" – det er en forklaring.
- RIKTIG: "HAN STOPPER IKKE" / "JEG DØR" / "NEI NEI NEI" – det er følelser.
- Andre eksempler: "HAN KOMMER", "STOPP NÅ", "DET GIKK GALT", "IKKE IGJEN", "SE DEG OM"
- ALDRI mer enn 4 ord. ALDRI beskrivende setninger.
- subheadline: tom string "" alltid, med mindre det er 1-2 ord som gir ekstra punch.`,
        },
        {
          role: 'user',
          content: [
            { type: 'image_url', image_url: { url: `data:image/jpeg;base64,${frameB64}`, detail: 'low' as const } },
            {
              type: 'text',
              text: [
                `Klipp: ${highlight.title ?? ''}`,
                `Kategori: ${highlight.category ?? ''}`,
                `Spill: ${vod?.category ?? vod?.title ?? ''}`,
                highlight.begrunnelse ? `Hva skjedde: ${highlight.begrunnelse}` : '',
                ytCopy?.tittel ? `Tittel: ${ytCopy.tittel}` : '',
                ttCopy?.caption ? `Caption: ${ttCopy.caption}` : '',
              ].filter(Boolean).join('\n'),
            },
          ],
        },
      ],
    });
    const m = (res.choices[0]?.message?.content ?? '').match(/\{[\s\S]*?\}/);
    if (m) return JSON.parse(m[0]);
  } catch {}

  const headline =
    highlight.category === 'FUNNY'       ? 'DETTE VAR SYKT' :
    highlight.category === 'CLUTCH'      ? 'KLARTE DET' :
    highlight.category === 'FAIL'        ? 'DET GIKK GALT' :
    highlight.category === 'RAGE'        ? 'HAN MISTET DET' :
    highlight.category === 'RP_MOMENT'   ? 'RP KAOS' :
    highlight.category === 'EDUCATIONAL' ? 'SE DETTE' :
    'SJEKK DETTE';
  return { headline, subheadline: '' };
}

// ── Design Helpers ────────────────────────────────────────────────────────────

interface AccentTheme {
  primary: string;
  secondary: string;
  glow: string;
}

function accentTheme(category: string): AccentTheme {
  switch (category) {
    case 'RAGE':        return { primary: '#FF3333', secondary: '#CC0000', glow: '#FF0000' };
    case 'CLUTCH':      return { primary: '#00FF87', secondary: '#00CC6A', glow: '#00FF87' };
    case 'FUNNY':       return { primary: '#FFD700', secondary: '#CC9900', glow: '#FFD700' };
    case 'RP_MOMENT':   return { primary: '#FF69B4', secondary: '#CC3380', glow: '#FF69B4' };
    case 'EDUCATIONAL': return { primary: '#00BFFF', secondary: '#0088CC', glow: '#00BFFF' };
    case 'FAIL':        return { primary: '#FF6600', secondary: '#CC4400', glow: '#FF6600' };
    case 'TACTICAL':    return { primary: '#9B59B6', secondary: '#7D3C98', glow: '#9B59B6' };
    default:            return { primary: '#FFFFFF', secondary: '#CCCCCC', glow: '#FFFFFF' };
  }
}

function sanitizeSvg(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function splitHeadline(text: string, maxCharsPerLine = 16): string[] {
  const words = text.trim().split(/\s+/);
  if (words.length <= 2 || text.length <= maxCharsPerLine) return [text];
  const mid = Math.ceil(words.length / 2);
  return [words.slice(0, mid).join(' '), words.slice(mid).join(' ')];
}

// Calculate font size that fits within available width for the given text
function calcFontSize(text: string, availW: number, maxFontH: number): number {
  const lines = splitHeadline(text, Math.ceil(availW / (maxFontH * 0.52)));
  const longestLine = lines.reduce((a, b) => a.length > b.length ? a : b, '');
  // Bebas Neue condensed: avg char width ≈ 0.52 × font height, spacing ≈ 2px per gap
  const charWidthRatio = 0.52;
  const spacing = (longestLine.length - 1) * 2;
  const maxByWidth = Math.floor((availW - spacing) / (longestLine.length * charWidthRatio));
  return Math.min(maxFontH, Math.max(32, maxByWidth));
}

// ── Color Grades ──────────────────────────────────────────────────────────────

type ColorGrade = 'gaming' | 'cinematic' | 'drama';

async function applyColorGrade(buf: Buffer, W: number, H: number, grade: ColorGrade): Promise<Buffer> {
  const sharp = require('sharp');

  if (grade === 'cinematic') {
    return sharp(buf)
      .resize(W, H, { fit: 'cover', position: 'entropy' })
      .sharpen({ sigma: 0.5, m1: 0.3, m2: 2.5 })
      .modulate({ brightness: 1.03, saturation: 1.28, hue: 5 })
      .linear(1.06, -8)
      .toBuffer();
  }

  if (grade === 'drama') {
    return sharp(buf)
      .resize(W, H, { fit: 'cover', position: 'entropy' })
      .sharpen({ sigma: 0.7, m1: 0.4, m2: 3.0 })
      .modulate({ brightness: 0.98, saturation: 1.55 })
      .linear(1.14, -20)
      .toBuffer();
  }

  // Gaming grade
  return sharp(buf)
    .resize(W, H, { fit: 'cover', position: 'entropy' })
    .sharpen({ sigma: 0.6, m1: 0.4, m2: 2.8 })
    .modulate({ brightness: 1.04, saturation: 1.38 })
    .linear(1.06, -6)
    .toBuffer();
}

// ── Subject Isolation ─────────────────────────────────────────────────────────

interface SubjectComposite {
  buf: Buffer;
  subjectPlaced: boolean;
  subjectLeft: number;
  subjectWidth: number;
}

async function buildSubjectComposite(
  frameBuf: Buffer,
  W: number,
  H: number,
  subjectBox: SubjectBox | null,
  layout: 'a' | 'b' | 'c',
  grade: ColorGrade
): Promise<SubjectComposite> {
  const sharp = require('sharp');
  const gradedFull = await applyColorGrade(frameBuf, W, H, grade);
  const noSubject: SubjectComposite = { buf: gradedFull, subjectPlaced: false, subjectLeft: 0, subjectWidth: W };

  const subjectArea = subjectBox ? (subjectBox.w * subjectBox.h) : 0;
  if (!subjectBox || subjectArea < 0.04) {
    log('SUBJECT_ISOLATION_SKIP', `no box or area too small (${(subjectArea * 100).toFixed(1)}%)`);
    return noSubject;
  }

  try {
    // Background: full frame, heavily blurred and darkened
    const bgBuf = await sharp(frameBuf)
      .resize(W, H, { fit: 'cover', position: 'entropy' })
      .blur(16)
      .modulate({ brightness: 0.38, saturation: 0.55 })
      .toBuffer();

    // Subject crop with padding
    const PAD = 0.06;
    const sx = Math.max(0, subjectBox.x - PAD);
    const sy = Math.max(0, subjectBox.y - PAD);
    const sw = Math.min(1 - sx, subjectBox.w + PAD * 2);
    const sh = Math.min(1 - sy, subjectBox.h + PAD * 2);

    const cropLeft = Math.round(sx * W);
    const cropTop  = Math.round(sy * H);
    const cropW    = Math.max(32, Math.min(W - cropLeft, Math.round(sw * W)));
    const cropH    = Math.max(32, Math.min(H - cropTop, Math.round(sh * H)));
    const aspectRatio = cropW / cropH;

    // Subject fills upper 65% of frame height max, ~52% of width
    const maxSubjH  = Math.round(H * 0.66);
    let subjTargetW = Math.round(W * 0.52);
    let subjTargetH = Math.round(subjTargetW / aspectRatio);
    if (subjTargetH > maxSubjH) {
      subjTargetH = maxSubjH;
      subjTargetW = Math.round(maxSubjH * aspectRatio);
    }
    subjTargetW = Math.max(64, subjTargetW);
    subjTargetH = Math.max(64, subjTargetH);

    // Extract from full-res, resize, and enhance subject
    const subjectBuf = await sharp(frameBuf)
      .resize(W, H, { fit: 'cover', position: 'entropy' })
      .extract({ left: cropLeft, top: cropTop, width: cropW, height: cropH })
      .resize(subjTargetW, subjTargetH, { fit: 'fill' })
      .sharpen({ sigma: 0.8, m1: 0.5, m2: 3.5 })
      .modulate({ brightness: 1.08, saturation: 1.25 })
      .toBuffer();

    // Position: A/B = upper-left, C = upper-right
    const placeLeft = (layout === 'c') ? Math.max(0, W - subjTargetW) : 0;
    const placeTop  = 0;

    const composite = await sharp(bgBuf)
      .composite([{ input: subjectBuf, left: placeLeft, top: placeTop }])
      .toBuffer();

    log('SUBJECT_ISOLATION_OK', `${subjTargetW}x${subjTargetH} placed at x=${placeLeft} subject=${subjectBox.w.toFixed(2)}x${subjectBox.h.toFixed(2)}`);
    return { buf: composite, subjectPlaced: true, subjectLeft: placeLeft, subjectWidth: subjTargetW };

  } catch (e: any) {
    log('SUBJECT_ISOLATION_FAILED', e.message?.slice(0, 100));
    return noSubject;
  }
}

// ── SVG: font declaration helper ─────────────────────────────────────────────

function fontDeclaration(fontPath: string | null): { decl: string; headFont: string } {
  if (fontPath && fs.existsSync(fontPath)) {
    return {
      decl: `@font-face { font-family: 'BebasNeue'; src: url('file://${fontPath}'); font-weight: normal; font-style: normal; }`,
      headFont: 'BebasNeue',
    };
  }
  return {
    decl: '',
    headFont: FONT_FALLBACK,
  };
}

// ── Layout A: Gaming Pro (subject upper-left, large text bottom) ──────────────

function svgLayoutA(p: {
  headline: string; subheadline: string; category: string;
  channelName: string; W: number; H: number; fontPath: string | null;
  subjectPlaced: boolean; subjectWidth: number;
}): string {
  const { headline, subheadline, category, channelName, W, H, fontPath, subjectPlaced, subjectWidth } = p;
  const { primary, glow: glowColor } = accentTheme(category);
  const { decl, headFont } = fontDeclaration(fontPath);
  const bodyFont = "'DejaVu Sans', 'Liberation Sans', Arial, sans-serif";

  const safeHead = sanitizeSvg(headline.toUpperCase());
  const safeSub  = sanitizeSvg(subheadline || '');
  const safeCh   = sanitizeSvg((channelName || 'GLENVEX').toUpperCase());
  const safeCat  = sanitizeSvg(category || '');

  // Text zone: right portion if subject placed, full width otherwise
  const textZoneLeft  = subjectPlaced ? Math.round(subjectWidth * 0.92) : 0;
  const textZoneW     = W - textZoneLeft - 20;

  // Font size: large, height-based, capped by text zone width
  const wordCount = headline.trim().split(/\s+/).length;
  const maxFontH  = Math.round(H * (wordCount <= 2 ? 0.28 : wordCount <= 3 ? 0.22 : 0.17));
  const hSize     = calcFontSize(safeHead, textZoneW, maxFontH);
  const sSize     = Math.round(hSize * 0.38);
  const chSize    = Math.round(W / 44);
  const badgeSize = Math.round(W / 38);
  const hStroke   = Math.max(6, Math.round(hSize / 7));
  const sStroke   = Math.max(2, Math.round(sSize / 10));
  const accentBarH = Math.max(6, Math.round(H * 0.011));
  const leftBarW   = Math.max(8, Math.round(W * 0.010));

  const textCenterX = Math.round(textZoneLeft + textZoneW / 2);

  // Text bottom anchor: above the accent bar with breathing room
  const textBottomY  = H - accentBarH - Math.round(H * 0.06);
  const headLines    = splitHeadline(safeHead, Math.floor(textZoneW / (hSize * 0.54)));
  const lineSpacing  = hSize * 1.12;
  const totalTextH   = headLines.length * lineSpacing + (safeSub ? sSize * 1.6 : 0);
  const headTopY     = textBottomY - totalTextH;

  // Gradient: dark at bottom ~45% for text readability
  const gradStartY = Math.round(H * 0.42);

  const badgePad = 10;
  const badgeW = safeCat ? Math.max(50, safeCat.length * badgeSize * 0.62 + badgePad * 2) : 0;
  const badgeH = safeCat ? badgeSize + 12 : 0;

  const headTspans = headLines.map((line, i) =>
    `<tspan x="${textCenterX}" dy="${i === 0 ? 0 : lineSpacing}">${line}</tspan>`
  ).join('');

  return `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}">
  <defs>
    <style>${decl}</style>
    <linearGradient id="g-bot" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%"   stop-color="black" stop-opacity="0"/>
      <stop offset="25%"  stop-color="black" stop-opacity="0.05"/>
      <stop offset="60%"  stop-color="black" stop-opacity="0.65"/>
      <stop offset="82%"  stop-color="black" stop-opacity="0.88"/>
      <stop offset="100%" stop-color="black" stop-opacity="0.97"/>
    </linearGradient>
    <linearGradient id="g-top" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%"  stop-color="black" stop-opacity="0.5"/>
      <stop offset="20%" stop-color="black" stop-opacity="0"/>
    </linearGradient>
    <filter id="glow-h" x="-20%" y="-40%" width="140%" height="180%">
      <feGaussianBlur in="SourceAlpha" stdDeviation="12" result="blur"/>
      <feFlood flood-color="${glowColor}" flood-opacity="0.9" result="color"/>
      <feComposite in="color" in2="blur" operator="in" result="shadow"/>
      <feMerge><feMergeNode in="shadow"/><feMergeNode in="SourceGraphic"/></feMerge>
    </filter>
    <filter id="drop">
      <feDropShadow dx="0" dy="2" stdDeviation="5" flood-color="black" flood-opacity="0.95"/>
    </filter>
  </defs>
  <rect x="0" y="${gradStartY}" width="${W}" height="${H - gradStartY}" fill="url(#g-bot)"/>
  <rect x="0" y="0" width="${W}" height="${Math.round(H * 0.20)}" fill="url(#g-top)"/>
  <rect x="0" y="0" width="${leftBarW}" height="${H}" fill="${primary}"/>
  <rect x="0" y="${H - accentBarH}" width="${W}" height="${accentBarH}" fill="${primary}" opacity="0.95"/>
  ${safeCat ? `
  <rect x="${leftBarW + 12}" y="14" width="${badgeW}" height="${badgeH}" rx="4" fill="${primary}" opacity="0.92"/>
  <text x="${leftBarW + 12 + badgePad}" y="${14 + badgeH * 0.72}"
    font-family="${headFont}" font-weight="900" font-size="${badgeSize}px" fill="black" letter-spacing="1">${safeCat}</text>` : ''}
  <text x="${W - leftBarW - 16}" y="${badgeH + 24}" text-anchor="end"
    font-family="${headFont}" font-weight="900" font-size="${chSize}px"
    fill="${primary}" stroke="black" stroke-width="2" paint-order="stroke fill"
    filter="url(#drop)">${safeCh}</text>
  <text x="${textCenterX}" y="${headTopY + hSize}" text-anchor="middle" dominant-baseline="text-before-edge"
    font-family="${headFont}" font-weight="900" font-size="${hSize}px"
    fill="${primary}" stroke="black" stroke-width="${hStroke}" stroke-linejoin="round"
    paint-order="stroke fill" filter="url(#glow-h)" letter-spacing="2">${headTspans}</text>
  ${safeSub ? `<text x="${textCenterX}" y="${headTopY + headLines.length * lineSpacing + hSize + 6}" text-anchor="middle" dominant-baseline="text-before-edge"
    font-family="${bodyFont}" font-weight="bold" font-size="${sSize}px"
    fill="white" stroke="black" stroke-width="${sStroke}" stroke-linejoin="round"
    paint-order="stroke fill" filter="url(#drop)">${safeSub}</text>` : ''}
</svg>`;
}

// ── Layout B: Cinema (subject upper-left, letterbox, centered text) ───────────

function svgLayoutB(p: {
  headline: string; subheadline: string; category: string;
  channelName: string; W: number; H: number; fontPath: string | null;
  subjectPlaced: boolean; subjectWidth: number;
}): string {
  const { headline, subheadline, category, channelName, W, H, fontPath } = p;
  const { primary } = accentTheme(category);
  const { decl, headFont } = fontDeclaration(fontPath);
  const bodyFont = "'DejaVu Sans', 'Liberation Sans', Arial, sans-serif";

  const safeHead = sanitizeSvg(headline.toUpperCase());
  const safeSub  = sanitizeSvg(subheadline || '');
  const safeCh   = sanitizeSvg((channelName || 'GLENVEX').toUpperCase());
  const safeCat  = sanitizeSvg(category || '');

  const lbTop = Math.round(H * 0.11);
  const lbBot = Math.round(H * 0.09);

  const wordCount = headline.trim().split(/\s+/).length;
  const maxFontH  = Math.round(H * (wordCount <= 2 ? 0.27 : wordCount <= 3 ? 0.21 : 0.16));
  const hSize     = calcFontSize(safeHead, W - 80, maxFontH);
  const sSize     = Math.round(hSize * 0.36);
  const chSize    = Math.round(W / 40);
  const catSize   = Math.round(W / 42);
  const hStroke   = Math.max(6, Math.round(hSize / 7));
  const sStroke   = Math.max(2, Math.round(sSize / 10));

  const headLines  = splitHeadline(safeHead, Math.floor((W - 80) / (hSize * 0.54)));
  const lineSpacing = hSize * 1.1;
  const totalTextH  = headLines.length * lineSpacing + (safeSub ? sSize * 1.7 : 0);
  const textBottomY = H - lbBot - Math.round(H * 0.04);
  const headTopY    = textBottomY - totalTextH;
  const gradStartY  = Math.round(H * 0.40);

  const headTspans = headLines.map((line, i) =>
    `<tspan x="${W / 2}" dy="${i === 0 ? 0 : lineSpacing}">${line}</tspan>`
  ).join('');

  return `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}">
  <defs>
    <style>${decl}</style>
    <radialGradient id="vig" cx="50%" cy="50%" r="72%" gradientUnits="objectBoundingBox">
      <stop offset="0%"   stop-color="black" stop-opacity="0"/>
      <stop offset="60%"  stop-color="black" stop-opacity="0.15"/>
      <stop offset="100%" stop-color="black" stop-opacity="0.70"/>
    </radialGradient>
    <linearGradient id="g-bot-b" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%"   stop-color="black" stop-opacity="0"/>
      <stop offset="45%"  stop-color="black" stop-opacity="0.55"/>
      <stop offset="100%" stop-color="black" stop-opacity="0.95"/>
    </linearGradient>
    <filter id="glow-b" x="-20%" y="-40%" width="140%" height="180%">
      <feGaussianBlur in="SourceAlpha" stdDeviation="14" result="blur"/>
      <feFlood flood-color="${primary}" flood-opacity="0.75" result="color"/>
      <feComposite in="color" in2="blur" operator="in" result="shadow"/>
      <feMerge><feMergeNode in="shadow"/><feMergeNode in="SourceGraphic"/></feMerge>
    </filter>
    <filter id="drop-b">
      <feDropShadow dx="0" dy="2" stdDeviation="5" flood-color="black" flood-opacity="0.95"/>
    </filter>
  </defs>
  <rect x="0" y="0" width="${W}" height="${H}" fill="url(#vig)"/>
  <rect x="0" y="${gradStartY}" width="${W}" height="${H - gradStartY}" fill="url(#g-bot-b)"/>
  <rect x="0" y="0" width="${W}" height="${lbTop}" fill="black"/>
  <rect x="0" y="${H - lbBot}" width="${W}" height="${lbBot}" fill="black"/>
  <rect x="0" y="${lbTop - 2}" width="${W}" height="2" fill="${primary}" opacity="0.85"/>
  <rect x="0" y="${H - lbBot}" width="${W}" height="2" fill="${primary}" opacity="0.85"/>
  <text x="${W / 2}" y="${lbTop * 0.62}" text-anchor="middle" dominant-baseline="middle"
    font-family="${headFont}" font-weight="900" font-size="${chSize}px"
    fill="white" stroke="black" stroke-width="2" paint-order="stroke fill"
    filter="url(#drop-b)" letter-spacing="4">${safeCh}</text>
  ${safeCat ? `<text x="20" y="${H - lbBot / 2}" dominant-baseline="middle"
    font-family="${headFont}" font-weight="900" font-size="${catSize}px"
    fill="${primary}" filter="url(#drop-b)" letter-spacing="1">${safeCat}</text>` : ''}
  <text x="${W / 2}" y="${headTopY}" text-anchor="middle" dominant-baseline="text-before-edge"
    font-family="${headFont}" font-weight="900" font-size="${hSize}px"
    fill="white" stroke="black" stroke-width="${hStroke}" stroke-linejoin="round"
    paint-order="stroke fill" filter="url(#glow-b)" letter-spacing="2">${headTspans}</text>
  ${safeSub ? `<text x="${W / 2}" y="${headTopY + headLines.length * lineSpacing + 8}" text-anchor="middle" dominant-baseline="text-before-edge"
    font-family="${bodyFont}" font-weight="bold" font-size="${sSize}px"
    fill="white" stroke="black" stroke-width="${sStroke}" stroke-linejoin="round"
    paint-order="stroke fill" filter="url(#drop-b)">${safeSub}</text>` : ''}
</svg>`;
}

// ── Layout C: Impact Block (subject upper-right, text bottom-left) ────────────

function svgLayoutC(p: {
  headline: string; subheadline: string; category: string;
  channelName: string; W: number; H: number; fontPath: string | null;
  subjectPlaced: boolean; subjectWidth: number;
}): string {
  const { headline, subheadline, category, channelName, W, H, fontPath, subjectPlaced, subjectWidth } = p;
  const { primary, secondary } = accentTheme(category);
  const { decl, headFont } = fontDeclaration(fontPath);
  const bodyFont = "'DejaVu Sans', 'Liberation Sans', Arial, sans-serif";

  const safeHead = sanitizeSvg(headline.toUpperCase());
  const safeSub  = sanitizeSvg(subheadline || '');
  const safeCh   = sanitizeSvg((channelName || 'GLENVEX').toUpperCase());
  const safeCat  = sanitizeSvg(category || '');

  // Text zone: left portion if subject on right
  const textZoneW = subjectPlaced ? Math.round((W - subjectWidth) * 1.05) : W;
  const textZoneW2 = Math.max(200, Math.min(W - 40, textZoneW));
  const padL = Math.round(W * 0.035);

  const wordCount = headline.trim().split(/\s+/).length;
  const maxFontH  = Math.round(H * (wordCount <= 2 ? 0.28 : wordCount <= 3 ? 0.22 : 0.17));
  const hSize     = calcFontSize(safeHead, textZoneW2 - padL * 2, maxFontH);
  const sSize     = Math.round(hSize * 0.38);
  const chSize    = Math.round(W / 44);
  const badgeSize = Math.round(W / 38);
  const hStroke   = Math.max(6, Math.round(hSize / 7));
  const sStroke   = Math.max(2, Math.round(sSize / 10));

  const panelY = Math.round(H * 0.66);
  const panelH = H - panelY;

  const headLines  = splitHeadline(safeHead, Math.floor((textZoneW2 - padL * 2) / (hSize * 0.54)));
  const lineSpacing = hSize * 1.1;
  const headY = panelY + Math.round(panelH * 0.14);

  const gradStartY = Math.round(H * 0.35);

  const badgePad = 10;
  const badgeW = safeCat ? Math.max(50, safeCat.length * badgeSize * 0.62 + badgePad * 2) : 0;
  const badgeH = safeCat ? badgeSize + 12 : 0;
  const badgeX = W - badgeW - 16;

  const headTspans = headLines.map((line, i) =>
    `<tspan x="${padL}" dy="${i === 0 ? 0 : lineSpacing}">${line}</tspan>`
  ).join('');

  return `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}">
  <defs>
    <style>${decl}</style>
    <radialGradient id="vig-c" cx="50%" cy="50%" r="70%" gradientUnits="objectBoundingBox">
      <stop offset="0%"   stop-color="black" stop-opacity="0"/>
      <stop offset="55%"  stop-color="black" stop-opacity="0.18"/>
      <stop offset="100%" stop-color="black" stop-opacity="0.80"/>
    </radialGradient>
    <linearGradient id="g-top-c" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%"  stop-color="black" stop-opacity="0.60"/>
      <stop offset="25%" stop-color="black" stop-opacity="0"/>
    </linearGradient>
    <linearGradient id="g-bot-c" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%"   stop-color="black" stop-opacity="0"/>
      <stop offset="50%"  stop-color="black" stop-opacity="0.40"/>
      <stop offset="100%" stop-color="black" stop-opacity="0.70"/>
    </linearGradient>
    <filter id="drop-c">
      <feDropShadow dx="0" dy="2" stdDeviation="4" flood-color="black" flood-opacity="1"/>
    </filter>
  </defs>
  <rect x="0" y="0" width="${W}" height="${H}" fill="url(#vig-c)"/>
  <rect x="0" y="0" width="${W}" height="${Math.round(H * 0.28)}" fill="url(#g-top-c)"/>
  <rect x="0" y="${gradStartY}" width="${W}" height="${H - gradStartY}" fill="url(#g-bot-c)"/>
  <rect x="0" y="${panelY}" width="${textZoneW2}" height="${panelH}" fill="${primary}" opacity="0.92"/>
  <rect x="0" y="${panelY}" width="${textZoneW2}" height="3" fill="white" opacity="0.5"/>
  <text x="${padL}" y="${headY}" dominant-baseline="text-before-edge"
    font-family="${headFont}" font-weight="900" font-size="${hSize}px"
    fill="white" stroke="black" stroke-width="${hStroke}" stroke-linejoin="round"
    paint-order="stroke fill" filter="url(#drop-c)" letter-spacing="2">${headTspans}</text>
  ${safeSub ? `<text x="${padL}" y="${headY + headLines.length * lineSpacing + 8}" dominant-baseline="text-before-edge"
    font-family="${bodyFont}" font-weight="bold" font-size="${sSize}px"
    fill="white" stroke="black" stroke-width="${sStroke}" stroke-linejoin="round"
    paint-order="stroke fill" filter="url(#drop-c)">${safeSub}</text>` : ''}
  <text x="16" y="${chSize + 14}" font-family="${headFont}" font-weight="900" font-size="${chSize}px"
    fill="white" filter="url(#drop-c)" letter-spacing="2">${safeCh}</text>
  ${safeCat ? `
  <rect x="${badgeX}" y="12" width="${badgeW}" height="${badgeH}" rx="4" fill="${secondary}" opacity="0.95"/>
  <text x="${badgeX + badgePad}" y="${12 + badgeH * 0.72}"
    font-family="${headFont}" font-weight="900" font-size="${badgeSize}px" fill="white" letter-spacing="1">${safeCat}</text>` : ''}
</svg>`;
}

// ── Composite One Variant ─────────────────────────────────────────────────────

async function buildOneVariant(
  videoUrl: string,
  frameT: number,
  copy: { headline: string; subheadline: string },
  category: string,
  channelName: string,
  layout: 'a' | 'b' | 'c',
  W: number,
  H: number,
  fontPath: string | null,
  label: string,
  subjectBox: SubjectBox | null
): Promise<Buffer | null> {
  log(`COMPOSITING_${label}`, `${W}x${H} layout=${layout} t=${frameT.toFixed(1)}s`);
  const hiBuf = await spawnFrame(videoUrl, frameT, W, H, 16_000);
  if (!hiBuf) { log(`FRAME_FETCH_FAILED_${label}`); return null; }

  try {
    const sharp = require('sharp');
    const grade: ColorGrade = layout === 'b' ? 'cinematic' : layout === 'c' ? 'drama' : 'gaming';

    // Subject isolation → background blur + subject overlay
    const { buf: composited, subjectPlaced, subjectLeft, subjectWidth } =
      await buildSubjectComposite(hiBuf, W, H, subjectBox, layout, grade);

    const svgBuilders = { a: svgLayoutA, b: svgLayoutB, c: svgLayoutC };
    const svg = svgBuilders[layout]({
      headline: copy.headline,
      subheadline: copy.subheadline,
      category,
      channelName,
      W,
      H,
      fontPath,
      subjectPlaced,
      subjectWidth,
    });

    return await sharp(composited)
      .composite([{ input: Buffer.from(svg), top: 0, left: 0 }])
      .png({ compressionLevel: 7 })
      .toBuffer();
  } catch (e: any) {
    log(`COMPOSITE_FAILED_${label}`, e.message?.slice(0, 200));
    return null;
  }
}

// ── Thumbnail Judge (Vision on finished thumbnail images) ─────────────────────

interface JudgeScore {
  thumbnailIdx: number; // 0-based
  clickScore: number;   // 0-100
  storyClear: boolean;
  verdict: string;
}

async function runThumbnailJudge(
  client: OpenAI,
  thumbnailBufs: Buffer[]
): Promise<{ winnerIdx: number; scores: JudgeScore[] }> {
  const fallback = { winnerIdx: 0, scores: thumbnailBufs.map((_, i) => ({ thumbnailIdx: i, clickScore: 50, storyClear: true, verdict: '' })) };
  if (thumbnailBufs.length <= 1) return fallback;

  const ctrl = new AbortController();
  const tid = setTimeout(() => ctrl.abort(), 22_000);
  try {
    const sharp = require('sharp');
    // Downscale for Vision (saves tokens, judge still sees layout+text)
    const previews = await Promise.all(
      thumbnailBufs.map(buf =>
        sharp(buf).resize(400, 225, { fit: 'fill' }).jpeg({ quality: 75 }).toBuffer()
      )
    );

    const res = await client.chat.completions.create({
      model: 'gpt-4o-mini',
      max_tokens: 300,
      temperature: 0,
      messages: [{
        role: 'user',
        content: [
          {
            type: 'text',
            text: `These are ${previews.length} YouTube gaming thumbnail drafts.
For each thumbnail judge:
1. Can someone understand the story/conflict/emotion in under 1 second without reading the title?
2. Is the main subject clearly visible and dominant?
3. Would a typical YouTube viewer click this thumbnail?
Pick the WINNER (highest click potential + clearest story).
Reply ONLY with valid JSON, no markdown:
{"scores":[{"n":1,"click":0-100,"clear":true,"verdict":"brief reason"},...], "winner":N}
N is 1-${previews.length}.`
          },
          ...previews.map(buf => ({
            type: 'image_url' as const,
            image_url: { url: `data:image/jpeg;base64,${buf.toString('base64')}`, detail: 'low' as const },
          })),
        ],
      }],
    }, { signal: ctrl.signal } as any);
    clearTimeout(tid);

    const raw = res.choices[0]?.message?.content ?? '';
    const clean = raw.replace(/^```[a-z]*\n?/i, '').replace(/\n?```$/i, '').trim();
    const m = clean.match(/\{[\s\S]*\}/);
    if (!m) throw new Error('No JSON');
    const d = JSON.parse(m[0]);

    const scores: JudgeScore[] = (d.scores ?? []).map((s: any, i: number) => ({
      thumbnailIdx: (s.n ?? i + 1) - 1,
      clickScore: Math.min(100, Math.max(0, s.click ?? 50)),
      storyClear: !!s.clear,
      verdict: String(s.verdict ?? '').slice(0, 100),
    }));

    const winnerIdx = Math.max(0, Math.min(thumbnailBufs.length - 1, (d.winner ?? 1) - 1));
    log('THUMBNAIL_JUDGE', `Winner: ${winnerIdx + 1}/${thumbnailBufs.length} scores=[${scores.map(s => s.clickScore).join(',')}]`);
    return { winnerIdx, scores };

  } catch (e: any) {
    clearTimeout(tid);
    log('THUMBNAIL_JUDGE_FAILED', e.message?.slice(0, 100));
    return fallback;
  }
}

// ── Quality Score ─────────────────────────────────────────────────────────────

function computeQualityScore(opts: {
  extractedFrames: number;
  visionUsed: boolean;
  headline: string;
  hasYoutube: boolean;
  hasTiktok: boolean;
  bestFramePct: number;
  fontAvailable: boolean;
  subjectPlaced: boolean;
  subjectType: SubjectType;
  ctrScore: number;
  boringRejected?: number;
}): number {
  let score = 0;
  score += Math.min(18, Math.round((opts.extractedFrames / FRAME_COUNT) * 18));
  score += opts.visionUsed ? 15 : 5;
  const words = opts.headline.trim().split(/\s+/).length;
  score += words <= 2 ? 25 : words === 3 ? 22 : words === 4 ? 15 : 5;
  score += opts.hasYoutube && opts.hasTiktok ? 12 : opts.hasYoutube || opts.hasTiktok ? 7 : 0;
  const pct = opts.bestFramePct;
  score += pct >= 15 && pct <= 85 ? 7 : 3;
  score += opts.subjectPlaced ? 13 : 0;
  score += opts.subjectType === 'face' ? 5 : opts.subjectType !== 'none' ? 3 : 0;
  score += opts.ctrScore >= 80 ? 8 : opts.ctrScore >= 60 ? 5 : opts.ctrScore >= 40 ? 2 : 0;
  // Bonus if boring frames were filtered (means winner is genuinely interesting)
  score += (opts.boringRejected ?? 0) > 0 ? 5 : 0;
  return Math.min(100, Math.round(score));
}

// ── Storage Upload ────────────────────────────────────────────────────────────

async function uploadPng(sb: any, buf: Buffer, sti: string): Promise<string | null> {
  try {
    const { error } = await sb.storage.from(STORAGE_BUCKET).upload(sti, buf, {
      contentType: 'image/png',
      upsert: true,
    });
    if (error) { log('UPLOAD_ERROR', JSON.stringify(error)); return null; }
    const { data } = sb.storage.from(STORAGE_BUCKET).getPublicUrl(sti);
    return (data as any)?.publicUrl ?? null;
  } catch (e: any) {
    log('UPLOAD_EXCEPTION', e.message?.slice(0, 200));
    return null;
  }
}

// ── Channel Name ──────────────────────────────────────────────────────────────

async function hentKanalNavn(sb: any, vodId: string): Promise<string> {
  try {
    const { data } = await sb.from('content_vods')
      .select('twitch_channel_name,title')
      .eq('id', vodId)
      .single();
    return data?.twitch_channel_name ?? '';
  } catch { return ''; }
}

// ── Main Builder ──────────────────────────────────────────────────────────────

export async function buildThumbnailV2(highlightId: string): Promise<void> {
  const sbUrl  = process.env.SUPABASE_URL;
  const sbKey  = process.env.SUPABASE_SERVICE_ROLE_KEY;
  const apiKey = process.env.OPENAI_API_KEY;
  if (!sbUrl || !sbKey || !apiKey) {
    log('ERROR', 'Mangler SUPABASE_URL / SERVICE_ROLE_KEY / OPENAI_API_KEY');
    return;
  }

  const sb     = createClient(sbUrl, sbKey, { realtime: { transport: require('ws') } });
  const client = new OpenAI({ apiKey });

  await sb.from('content_highlights').update({
    thumbnail_status: 'GENERATING',
    thumbnail_error:  null,
  }).eq('id', highlightId).in('thumbnail_status', ['PENDING', 'GENERATING']);
  await sb.from('content_highlights').update({ thumbnail_started_at: new Date().toISOString() }).eq('id', highlightId);

  log('JOB_CLAIMED', highlightId);
  logSystemEvent({ source: 'thumbnail', event_type: 'THUMBNAIL_JOB_CLAIMED', title: `Thumbnail V4 claim: ${highlightId.slice(0, 8)}`, severity: 'info', metadata: { highlight_id: highlightId } });

  try {
    // ── Fetch data ─────────────────────────────────────────────────────────
    const { data: h, error: hErr } = await sb.from('content_highlights')
      .select('id,vod_id,title,category,begrunnelse,clip_url,vertical_clip_url,clip_status')
      .eq('id', highlightId)
      .single();

    if (hErr || !h) throw new Error('Highlight ikke funnet');
    if (h.clip_status !== 'CLIPPED') throw new Error(`clip_status = ${h.clip_status}`);

    const videoUrl = h.clip_url ?? h.vertical_clip_url;
    if (!videoUrl) throw new Error('Ingen clip_url eller vertical_clip_url');

    const [vodRes, copiesRes] = await Promise.all([
      sb.from('content_vods').select('id,title,category').eq('id', h.vod_id).single(),
      sb.from('content_copy').select('platform,tittel,caption').eq('highlight_id', highlightId),
    ]);
    const vod    = vodRes.data;
    const copies = copiesRes.data ?? [];
    const game   = vod?.category ?? vod?.title ?? 'video game';
    const channel = await hentKanalNavn(sb, h.vod_id);

    // ── Font (file path, not base64) ────────────────────────────────────────
    const fontPath = await prepareFontPath();
    log(fontPath ? 'FONT_OK' : 'FONT_FALLBACK', fontPath ?? FONT_FALLBACK);

    // ── Frame extraction (20 frames) ────────────────────────────────────────
    log('FRAME_EXTRACTION_STARTED');
    logSystemEvent({ source: 'thumbnail', event_type: 'FRAME_EXTRACTION_STARTED', title: `Ekstraher ${FRAME_COUNT} frames: "${(h.title ?? '').slice(0, 60)}"`, severity: 'info', metadata: { highlight_id: highlightId, frame_count: FRAME_COUNT } });

    const duration  = await getClipDuration(videoUrl);
    const rawFrames = await extractCandidateFrames(videoUrl, duration);
    log('FRAMES_EXTRACTED', `${rawFrames.length}/${FRAME_COUNT} OK`);
    logSystemEvent({ source: 'thumbnail', event_type: 'FRAME_EXTRACTION_DONE', title: `${rawFrames.length}/${FRAME_COUNT} frames OK`, severity: 'info', metadata: { highlight_id: highlightId, frames: rawFrames.length } });

    if (rawFrames.length === 0) throw new Error('Ingen frames kunne ekstraheres');

    // ── Step 1: Heuristic score → top 5 candidates ──────────────────────────
    const scored = rawFrames
      .map(f => ({ ...f, score: scoreFrame(f) }))
      .sort((a, b) => b.score - a.score)
      .slice(0, TOP_CANDIDATES);

    // ── Step 2: Vision frame analysis – score + boring rejection ────────────
    logSystemEvent({ source: 'thumbnail', event_type: 'THUMBNAIL_FRAME_ANALYSIS_STARTED', title: `Vision frame-analyse (${scored.length} kandidater)`, severity: 'info', metadata: { highlight_id: highlightId, candidates: scored.length } });

    const frameAnalyses = await analyzeAllFrames(client, scored, h.category, game);

    // Sort by action score, filter boring first
    const nonBoring  = frameAnalyses.filter(a => !a.boring).sort((a, b) => b.actionScore - a.actionScore);
    const allSorted  = frameAnalyses.slice().sort((a, b) => b.actionScore - a.actionScore);
    const candidates = (nonBoring.length > 0 ? nonBoring : allSorted).slice(0, 3);

    const boringRejected = frameAnalyses.length - nonBoring.length;
    log('BORING_REJECTION', `${boringRejected}/${frameAnalyses.length} frames rejected as boring`);

    // NEEDS_MANUAL_REVIEW: every frame boring AND max actionScore < 20
    const maxAction = allSorted[0]?.actionScore ?? 0;
    if (boringRejected === frameAnalyses.length && maxAction < 20) {
      log('NEEDS_MANUAL_REVIEW', `all ${frameAnalyses.length} frames boring, max action=${maxAction}`);
      await sb.from('content_highlights').update({
        thumbnail_status: 'NEEDS_MANUAL_REVIEW',
        thumbnail_error: `Ingen interessant frame funnet (alle boring, max action ${maxAction}/100). Bruk manuell opplasting.`,
      }).eq('id', highlightId);
      logSystemEvent({ source: 'thumbnail', event_type: 'THUMBNAIL_FAILED', title: 'Thumbnail: NEEDS_MANUAL_REVIEW', description: `Alle frames boring – ingen konflikt/reaksjon funnet`, severity: 'warning', metadata: { highlight_id: highlightId } });
      return;
    }

    const bestCandidate = candidates[0];
    logSystemEvent({
      source: 'thumbnail', event_type: 'THUMBNAIL_FRAME_SELECTED',
      title: `Beste frame: t=${scored[bestCandidate.idx]?.t?.toFixed(1) ?? '?'}s action=${bestCandidate.actionScore}/100 subject=${bestCandidate.subjectType}`,
      severity: 'info',
      metadata: { highlight_id: highlightId, frame_t: scored[bestCandidate.idx]?.t, action_score: bestCandidate.actionScore, subject_type: bestCandidate.subjectType, boring_rejected: boringRejected },
    });

    // ── Step 3: Copy generation from best candidate's frame ──────────────────
    const copy = await generateCopy(client, h, vod, copies, scored[bestCandidate.idx].buf.toString('base64'));
    log('COPY_GENERATED', `"${copy.headline}" / "${copy.subheadline}"`);

    logSystemEvent({ source: 'thumbnail', event_type: 'THUMBNAIL_RENDER_STARTED', title: `Bygg ${candidates.length} thumbnail-drafts: "${copy.headline}"`, severity: 'info', metadata: { highlight_id: highlightId, headline: copy.headline, font: fontPath ? 'BebasNeue' : 'system', drafts: candidates.length } });

    // ── Step 4: Build Layout A drafts for all candidates (parallel) ──────────
    const draftResults = await Promise.all(
      candidates.map(analysis => {
        const frame = scored[analysis.idx];
        return buildOneVariant(videoUrl, frame.t, copy, h.category, channel, 'a', YT_W, YT_H, fontPath, `DRAFT_${analysis.idx}`, analysis.subjectBox)
          .then(buf => ({ buf, analysis, frameT: frame.t }));
      })
    );
    const validDrafts = draftResults.filter(d => d.buf !== null) as { buf: Buffer; analysis: FrameAnalysis; frameT: number }[];
    log('DRAFTS_BUILT', `${validDrafts.length}/${candidates.length} OK`);

    if (validDrafts.length === 0) throw new Error('Alle draft-builds feilet');

    // ── Step 5: Thumbnail Judge – Vision picks best finished thumbnail ────────
    let winnerDraft = validDrafts[0];
    let judgeScore  = 50;
    if (validDrafts.length > 1) {
      const { winnerIdx, scores } = await runThumbnailJudge(client, validDrafts.map(d => d.buf));
      winnerDraft = validDrafts[winnerIdx] ?? validDrafts[0];
      judgeScore  = scores[winnerIdx]?.clickScore ?? 50;
      log('JUDGE_RESULT', `Winner draft ${winnerIdx + 1}/${validDrafts.length} click=${judgeScore} subject=${winnerDraft.analysis.subjectType}`);
    }

    const usedFrameT    = winnerDraft.frameT;
    const winnerAnalysis = winnerDraft.analysis;
    const bestYtBuf     = winnerDraft.buf;           // reuse winning draft as Variant A
    const ttSource      = h.vertical_clip_url ?? h.clip_url;

    // ── Step 6: Build TikTok + Variants B/C for winner ──────────────────────
    const [bestTtBuf, ytBufB, ytBufC] = await Promise.all([
      buildOneVariant(ttSource,  usedFrameT, copy, h.category, channel, 'a', TT_W, TT_H, fontPath, 'TT_A',  winnerAnalysis.subjectBox),
      buildOneVariant(videoUrl,  usedFrameT, copy, h.category, channel, 'b', YT_W, YT_H, fontPath, 'YT_B',  winnerAnalysis.subjectBox),
      buildOneVariant(videoUrl,  usedFrameT, copy, h.category, channel, 'c', YT_W, YT_H, fontPath, 'YT_C',  winnerAnalysis.subjectBox),
    ]);

    const bestScore = computeQualityScore({
      extractedFrames: rawFrames.length,
      visionUsed: true,
      headline: copy.headline,
      hasYoutube: !!bestYtBuf,
      hasTiktok:  !!bestTtBuf,
      bestFramePct: scored[winnerAnalysis.idx]?.pct ?? 50,
      fontAvailable: !!fontPath,
      subjectPlaced: winnerAnalysis.subjectBox !== null,
      subjectType: winnerAnalysis.subjectType,
      ctrScore: judgeScore,
      boringRejected,
    });

    log('IMAGE_BUILD_DONE', `score=${bestScore} judge=${judgeScore} A=${!!bestYtBuf} B=${!!ytBufB} C=${!!ytBufC}`);
    logSystemEvent({
      source: 'thumbnail', event_type: 'THUMBNAIL_VARIANTS_GENERATED',
      title: `Varianter A/B/C generert (score: ${bestScore}/100, judge: ${judgeScore}/100)`,
      severity: 'info',
      metadata: { highlight_id: highlightId, score: bestScore, judge_score: judgeScore, has_a: !!bestYtBuf, has_b: !!ytBufB, has_c: !!ytBufC },
    });

    if (!bestYtBuf && !bestTtBuf) throw new Error('Compositing feilet for alle forsøk');

    // ── Upload ──────────────────────────────────────────────────────────────
    const wsId    = process.env.WORKSPACE_ID ?? '(ikke satt)';
    const baseSti = `content-factory/thumbnails/${h.vod_id}/${highlightId}`;
    log('UPLOAD_CTX', `bucket=${STORAGE_BUCKET} vod=${h.vod_id} highlight=${highlightId} ws=${wsId}`);
    logSystemEvent({ source: 'thumbnail', event_type: 'SUPABASE_UPLOAD_STARTED', title: 'Laster opp thumbnails (A+B+C)', severity: 'info', metadata: { highlight_id: highlightId, bucket: STORAGE_BUCKET } });

    async function uploadAndLog(buf: Buffer | null, sti: string, label: string): Promise<string | null> {
      if (!buf) { log(`UPLOAD_${label}_SKIP`, 'buffer null'); return null; }
      log(`UPLOAD_${label}_START`, `size=${buf.length} path=${sti}`);
      const url = await uploadPng(sb, buf, sti);
      log(`UPLOAD_${label}_RESULT`, url ? `OK url=...${url.slice(-60)}` : `FAILED`);
      return url;
    }

    const ytUrl  = await uploadAndLog(bestYtBuf, `${baseSti}_youtube.png`,   'A');
    const ttUrl  = await uploadAndLog(bestTtBuf, `${baseSti}_tiktok.png`,    'TIKTOK');
    const ytUrlB = await uploadAndLog(ytBufB,    `${baseSti}_variant_b.png`, 'B');
    const ytUrlC = await uploadAndLog(ytBufC,    `${baseSti}_variant_c.png`, 'C');

    log('UPLOAD_SUMMARY', `A=${ytUrl ? 'OK' : 'NULL'} TT=${ttUrl ? 'OK' : 'NULL'} B=${ytUrlB ? 'OK' : 'NULL'} C=${ytUrlC ? 'OK' : 'NULL'}`);

    if (!ytUrl && !ttUrl) throw new Error('Opplasting til Supabase Storage feilet (begge null)');
    logSystemEvent({ source: 'thumbnail', event_type: 'SUPABASE_UPLOAD_DONE', title: 'Thumbnails lastet opp', severity: 'info', metadata: { highlight_id: highlightId, yt_url: ytUrl, tt_url: ttUrl, b_url: ytUrlB, c_url: ytUrlC } });

    // ── Primary DB update ───────────────────────────────────────────────────
    log('DB_UPDATE_START', `highlight_id=${highlightId}`);
    const { data: doneRows, error: doneErr } = await sb.from('content_highlights').update({
      thumbnail_status:       'DONE',
      thumbnail_youtube_url:  ytUrl  ?? null,
      thumbnail_tiktok_url:   ttUrl  ?? null,
      thumbnail_headline:     copy.headline,
      thumbnail_subheadline:  copy.subheadline || null,
      thumbnail_generated_at: new Date().toISOString(),
      thumbnail_error:        null,
      thumbnail_prompt:       null,
    }).eq('id', highlightId).select('id,thumbnail_status,thumbnail_youtube_url');

    if (doneErr) {
      log('DB_UPDATE_FAILED', `err=${doneErr.message}`);
      throw new Error('DB DONE-oppdatering feilet: ' + doneErr.message);
    }
    log('DB_UPDATE_SUCCESS', `affected=${doneRows?.length ?? 0} status=${doneRows?.[0]?.thumbnail_status ?? 'ukjent'} yt=${doneRows?.[0]?.thumbnail_youtube_url ? 'SET' : 'NULL'}`);
    if ((doneRows?.length ?? 0) === 0) log('DB_UPDATE_WARN', `0 rader oppdatert`);

    await sb.from('content_highlights').update({
      thumbnail_source_frame:  usedFrameT,
      thumbnail_quality_score: bestScore,
    }).eq('id', highlightId);

    // ── Variant B/C + CTR columns ───────────────────────────────────────────
    try {
      const { error: varErr } = await sb.from('content_highlights').update({
        thumbnail_variant_b_url: ytUrlB ?? null,
        thumbnail_variant_c_url: ytUrlC ?? null,
        thumbnail_ctr_score:     judgeScore,
        thumbnail_ctr_reason:    winnerAnalysis.reason || null,
      }).eq('id', highlightId);
      if (varErr) {
        log('VARIANT_COLS_SKIP', varErr.message?.slice(0, 120));
      } else {
        log('VARIANT_COLS_OK', `B=${ytUrlB ? 'SET' : 'NULL'} C=${ytUrlC ? 'SET' : 'NULL'} ctr=${judgeScore}`);
      }
    } catch (variantErr: any) {
      log('VARIANT_COLS_SKIP', variantErr.message?.slice(0, 120));
    }

    // ── DB read-back verification ───────────────────────────────────────────
    try {
      const { data: rbRow, error: rbErr } = await sb.from('content_highlights')
        .select('id,thumbnail_status,thumbnail_youtube_url,thumbnail_tiktok_url,thumbnail_variant_b_url,thumbnail_variant_c_url,thumbnail_ctr_score')
        .eq('id', highlightId)
        .single();
      log('DB_READBACK', rbErr
        ? `READ_ERROR: ${rbErr.message?.slice(0, 80)}`
        : `status=${rbRow?.thumbnail_status} yt=${rbRow?.thumbnail_youtube_url ? 'SET' : 'NULL'} tt=${rbRow?.thumbnail_tiktok_url ? 'SET' : 'NULL'} b=${rbRow?.thumbnail_variant_b_url ? 'SET' : 'NULL'} c=${rbRow?.thumbnail_variant_c_url ? 'SET' : 'NULL'} ctr=${rbRow?.thumbnail_ctr_score ?? 'NULL'}`
      );
    } catch {}

    log('THUMBNAIL_V4_DONE', `score=${bestScore} judge=${judgeScore} frame=${usedFrameT.toFixed(1)}s subject=${winnerAnalysis.subjectType} boring_rejected=${boringRejected}`);
    logSystemEvent({
      source: 'thumbnail', event_type: 'THUMBNAIL_COMPLETED',
      title: `Thumbnail FERDIG – score ${bestScore}/100 judge ${judgeScore}/100`,
      description: `"${(h.title ?? '').slice(0, 80)}"`,
      severity: 'info',
      metadata: { highlight_id: highlightId, score: bestScore, judge_score: judgeScore, frame_t: usedFrameT, yt_url: ytUrl, tt_url: ttUrl, b_url: ytUrlB, c_url: ytUrlC, subject_type: winnerAnalysis.subjectType, boring_rejected: boringRejected },
    });

  } catch (err: any) {
    const msg = (err.message ?? 'Ukjent feil').slice(0, 300);
    log('FAILED', msg);
    logSystemEvent({ source: 'thumbnail', event_type: 'THUMBNAIL_FAILED', title: 'Thumbnail FEILET', description: msg, severity: 'error', metadata: { highlight_id: highlightId, error: msg } });
    try {
      await sb.from('content_highlights').update({
        thumbnail_status: 'FAILED',
        thumbnail_error:  msg,
      }).eq('id', highlightId);
    } catch {}
  }
}
