/**
 * Thumbnail Builder V3 – AAA Premium Gaming Thumbnail
 *
 * Architecture: Frame-first. DALL-E is NOT used.
 * Text is generated by GPT, rendered by Sharp+SVG. Never by AI.
 *
 * Flow:
 *  1. Download Bebas Neue font on first use → /tmp/glenvex-fonts/
 *  2. Extract 20 frames spread through the clip
 *  3. Score frames (brightness + position heuristic)
 *  4. Top 5 → GPT-4o Vision → pick best frame + CTR score + reason
 *  5. Generate headline + subheadline (GPT sees chosen frame)
 *  6. Build Variant A (Gaming grade + Pro layout) with quality retry
 *  7. Build Variant B (Cinematic grade + Cinema layout)
 *  8. Build Variant C (Drama grade + Impact Block layout)
 *  9. Upload all to Supabase Storage
 * 10. Update DB: DONE + variant URLs + CTR score/reason
 */

import { spawn } from 'child_process';
import { promisify } from 'util';
import { exec } from 'child_process';
import * as fs from 'fs';
import * as path from 'path';
import OpenAI from 'openai';
import { createClient } from '@supabase/supabase-js';
import { logSystemEvent } from './systemEvents';

const execAsync = promisify(exec);
const STORAGE_BUCKET = process.env.STORAGE_BUCKET ?? 'glenvex-assets';

// ── Config ────────────────────────────────────────────────────────────────────

const FRAME_COUNT       = 20;
const TOP_CANDIDATES    = 5;
const MAX_RETRIES       = 2;
const QUALITY_THRESHOLD = 70;

const YT_W = 1280;
const YT_H = 720;
const TT_W = 1080;
const TT_H = 1920;

// ── Font ──────────────────────────────────────────────────────────────────────

const FONT_DIR  = '/tmp/glenvex-fonts';
const FONT_PATH = path.join(FONT_DIR, 'BebasNeue.ttf');
const FONT_URL  = 'https://github.com/google/fonts/raw/main/ofl/bebasneue/BebasNeue-Regular.ttf';

let _fontBase64: string | null = null;

async function getFontBase64(): Promise<string | null> {
  if (_fontBase64) return _fontBase64;
  try {
    if (!fs.existsSync(FONT_PATH)) {
      fs.mkdirSync(FONT_DIR, { recursive: true });
      const res = await fetch(FONT_URL, { signal: AbortSignal.timeout(15_000) });
      if (!res.ok) return null;
      fs.writeFileSync(FONT_PATH, Buffer.from(await res.arrayBuffer()));
      log('FONT_DOWNLOADED', FONT_PATH);
    }
    _fontBase64 = fs.readFileSync(FONT_PATH).toString('base64');
    return _fontBase64;
  } catch (e: any) {
    log('FONT_DOWNLOAD_FAILED', e.message?.slice(0, 100));
    return null;
  }
}

// ── Logging ───────────────────────────────────────────────────────────────────

function log(step: string, detail = '') {
  console.log(`[ThumbnailV3] ${step}${detail ? ': ' + detail : ''}`);
}

// ── Frame Extraction ──────────────────────────────────────────────────────────

function spawnFrame(
  videoUrl: string,
  t: number,
  w: number,
  h: number,
  timeoutMs = 14_000
): Promise<Buffer | null> {
  return new Promise(resolve => {
    const proc = spawn('ffmpeg', [
      '-ss', String(Math.max(0.1, t)),
      '-i', videoUrl,
      '-vframes', '1',
      '-f', 'image2',
      '-vcodec', 'mjpeg',
      '-q:v', '2',
      '-vf', `scale=${w}:${h}:force_original_aspect_ratio=decrease,pad=${w}:${h}:(ow-iw)/2:(oh-ih)/2:black,setsar=1`,
      'pipe:1',
    ]);
    const chunks: Buffer[] = [];
    proc.stdout?.on('data', (c: Buffer) => chunks.push(c));
    const tid = setTimeout(() => { try { proc.kill('SIGKILL'); } catch {} resolve(null); }, timeoutMs);
    proc.on('close', (code: number) => {
      clearTimeout(tid);
      resolve(code === 0 && chunks.length > 0 ? Buffer.concat(chunks) : null);
    });
    proc.on('error', () => { clearTimeout(tid); resolve(null); });
  });
}

async function getClipDuration(clipUrl: string): Promise<number> {
  try {
    const { stdout } = await execAsync(
      `ffprobe -v error -show_entries format=duration -of csv=p=0 "${clipUrl}"`,
      { timeout: 10_000 }
    );
    const d = parseFloat(stdout.trim());
    return d > 0 && isFinite(d) ? d : 30;
  } catch { return 30; }
}

interface RawFrame {
  idx: number;
  t: number;
  pct: number;
  buf: Buffer;
}

async function extractCandidateFrames(clipUrl: string, duration: number): Promise<RawFrame[]> {
  const percentages = Array.from({ length: FRAME_COUNT }, (_, i) =>
    5 + (i * 90 / (FRAME_COUNT - 1))
  );
  const timestamps = percentages.map(p => Math.max(0.5, (duration * p) / 100));

  const frames: RawFrame[] = [];
  const BATCH = 4;
  for (let i = 0; i < timestamps.length; i += BATCH) {
    const batch = timestamps.slice(i, i + BATCH);
    const results = await Promise.all(
      batch.map(async (t, j) => {
        const buf = await spawnFrame(clipUrl, t, 640, 360, 12_000);
        return buf ? { idx: i + j, t, pct: percentages[i + j], buf } : null;
      })
    );
    frames.push(...(results.filter(Boolean) as RawFrame[]));
  }
  return frames;
}

// ── Frame Scoring ─────────────────────────────────────────────────────────────

function scoreBrightness(buf: Buffer): number {
  const start = Math.floor(buf.length * 0.3);
  const end   = Math.floor(buf.length * 0.7);
  let sum = 0; let n = 0;
  for (let i = start; i < end; i += 50) { sum += buf[i]; n++; }
  const avg = n > 0 ? sum / n : 128;
  if (avg < 35)  return 0;
  if (avg > 225) return 20;
  if (avg < 65)  return 35;
  return 100;
}

function scorePosition(pct: number): number {
  if (pct < 5 || pct > 95)   return 10;
  if (pct < 12 || pct > 88)  return 50;
  return 100;
}

function scoreFrame(frame: RawFrame): number {
  return Math.round((scoreBrightness(frame.buf) * 0.5) + (scorePosition(frame.pct) * 0.5));
}

// ── CTR Vision Analysis ───────────────────────────────────────────────────────

interface CtrResult {
  selectedIdx: number;
  ctrScore: number;
  reason: string;
}

async function selectBestFrameWithCtr(
  client: OpenAI,
  frames: RawFrame[],
  category: string,
  game: string
): Promise<CtrResult> {
  const fallback: CtrResult = {
    selectedIdx: Math.floor(frames.length / 2),
    ctrScore: 50,
    reason: '',
  };
  if (frames.length <= 1) return { selectedIdx: 0, ctrScore: 60, reason: 'Kun ett frame tilgjengelig' };

  const ctrl = new AbortController();
  const tid = setTimeout(() => ctrl.abort(), 12_000);
  try {
    const res = await client.chat.completions.create({
      model: 'gpt-4o-mini',
      max_tokens: 80,
      temperature: 0,
      messages: [{
        role: 'user',
        content: [
          {
            type: 'text',
            text: `These ${frames.length} frames are from a ${game || 'video game'} gaming clip (type: ${category || 'general'}).
Which frame makes the BEST YouTube gaming thumbnail?
Prioritize: visible reactions/faces, dramatic action, strong contrast, emotional impact.
Reply ONLY with valid JSON on one line: {"selected":N,"ctr_score":0-100,"reason":"brief reason"}
N is 1–${frames.length}. ctr_score is predicted click-through quality.`,
          },
          ...frames.map(f => ({
            type: 'image_url' as const,
            image_url: { url: `data:image/jpeg;base64,${f.buf.toString('base64')}`, detail: 'low' as const },
          })),
        ],
      }],
    }, { signal: ctrl.signal } as any);
    clearTimeout(tid);

    const text = res.choices[0]?.message?.content ?? '';
    const m = text.match(/\{[\s\S]*?\}/);
    if (m) {
      const d = JSON.parse(m[0]);
      const idx = (d.selected ?? 1) - 1;
      if (idx >= 0 && idx < frames.length) {
        const ctrScore = Math.min(100, Math.max(0, d.ctr_score ?? 50));
        const reason   = (d.reason ?? '').slice(0, 200);
        log('CTR_VISION', `Frame ${idx + 1}/${frames.length} score=${ctrScore} t=${frames[idx].t.toFixed(1)}s`);
        return { selectedIdx: idx, ctrScore, reason };
      }
    }
  } catch { clearTimeout(tid); }

  log('CTR_VISION_FALLBACK', 'Bruker midterste frame');
  return fallback;
}

// ── Copy Generation ───────────────────────────────────────────────────────────

async function generateCopy(
  client: OpenAI,
  highlight: any,
  vod: any,
  copies: any[],
  frameB64: string
): Promise<{ headline: string; subheadline: string }> {
  const ytCopy = copies.find((c: any) => c.platform === 'youtube');
  const ttCopy = copies.find((c: any) => c.platform === 'tiktok');

  try {
    const res = await client.chat.completions.create({
      model: 'gpt-4o-mini',
      max_tokens: 100,
      temperature: 0.85,
      messages: [
        {
          role: 'system',
          content: `Du lager tekst til AAA gaming YouTube-thumbnails. Svar KUN med JSON: {"headline":"...","subheadline":"..."}

headline: 2-4 ORD, STORE BOKSTAVER, norsk, sjokkerende/clickbait-energisk. Eksempler: "DETTE GIKK GALT", "HAN MISTET DET", "BOSSEN FALT ENDELIG", "CHAT MISTET DET", "100% KLARTE DET", "DET VAR IKKE PLANEN", "ALDRI GJØR DETTE"
subheadline: 3-6 ord norsk, bygger på headlinen. Tomt string ("") hvis ikke naturlig.
Unngå generiske fraser. Tenk clickbait-energi.`,
        },
        {
          role: 'user',
          content: [
            { type: 'image_url', image_url: { url: `data:image/jpeg;base64,${frameB64}`, detail: 'low' as const } },
            {
              type: 'text',
              text: [
                `Klipp: ${highlight.title ?? ''}`,
                `Kategori: ${highlight.category ?? ''}`,
                `Spill: ${vod?.category ?? vod?.title ?? ''}`,
                highlight.begrunnelse ? `Hva skjedde: ${highlight.begrunnelse}` : '',
                ytCopy?.tittel ? `Tittel: ${ytCopy.tittel}` : '',
                ttCopy?.caption ? `Caption: ${ttCopy.caption}` : '',
              ].filter(Boolean).join('\n'),
            },
          ],
        },
      ],
    });
    const m = (res.choices[0]?.message?.content ?? '').match(/\{[\s\S]*?\}/);
    if (m) return JSON.parse(m[0]);
  } catch {}

  const headline =
    highlight.category === 'FUNNY'       ? 'DETTE VAR SYKT' :
    highlight.category === 'CLUTCH'      ? 'KLARTE DET AKKURAT' :
    highlight.category === 'FAIL'        ? 'DETTE GIKK GALT' :
    highlight.category === 'RAGE'        ? 'HAN MISTET DET' :
    highlight.category === 'RP_MOMENT'   ? 'RP BLE KAOS' :
    highlight.category === 'EDUCATIONAL' ? 'LÆR DETTE NESTE' :
    'SJEKK DETTE';
  return { headline, subheadline: '' };
}

// ── Design Helpers ────────────────────────────────────────────────────────────

interface AccentTheme {
  primary: string;
  secondary: string;
  glow: string;
}

function accentTheme(category: string): AccentTheme {
  switch (category) {
    case 'RAGE':        return { primary: '#FF3333', secondary: '#CC0000', glow: '#FF0000' };
    case 'CLUTCH':      return { primary: '#00FF87', secondary: '#00CC6A', glow: '#00FF87' };
    case 'FUNNY':       return { primary: '#FFD700', secondary: '#CC9900', glow: '#FFD700' };
    case 'RP_MOMENT':   return { primary: '#FF69B4', secondary: '#CC3380', glow: '#FF69B4' };
    case 'EDUCATIONAL': return { primary: '#00BFFF', secondary: '#0088CC', glow: '#00BFFF' };
    case 'FAIL':        return { primary: '#FF6600', secondary: '#CC4400', glow: '#FF6600' };
    case 'TACTICAL':    return { primary: '#9B59B6', secondary: '#7D3C98', glow: '#9B59B6' };
    default:            return { primary: '#FFFFFF', secondary: '#CCCCCC', glow: '#FFFFFF' };
  }
}

function sanitizeSvg(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function splitHeadline(text: string, maxCharsPerLine = 16): string[] {
  const words = text.trim().split(/\s+/);
  if (words.length <= 2 || text.length <= maxCharsPerLine) return [text];
  const mid = Math.ceil(words.length / 2);
  return [words.slice(0, mid).join(' '), words.slice(mid).join(' ')];
}

// ── Color Grades ──────────────────────────────────────────────────────────────

type ColorGrade = 'gaming' | 'cinematic' | 'drama';

async function applyColorGrade(buf: Buffer, W: number, H: number, grade: ColorGrade): Promise<Buffer> {
  const sharp = require('sharp');

  if (grade === 'cinematic') {
    // Film-like: warm hue shift, moderate contrast, refined look
    return sharp(buf)
      .resize(W, H, { fit: 'cover', position: 'entropy' })
      .sharpen({ sigma: 0.5, m1: 0.3, m2: 2.5 })
      .modulate({ brightness: 1.03, saturation: 1.28, hue: 5 })
      .linear(1.06, -8)
      .toBuffer();
  }

  if (grade === 'drama') {
    // Maximum impact: crushed blacks, boosted saturation, strong contrast
    return sharp(buf)
      .resize(W, H, { fit: 'cover', position: 'entropy' })
      .sharpen({ sigma: 0.7, m1: 0.4, m2: 3.0 })
      .modulate({ brightness: 0.98, saturation: 1.55 })
      .linear(1.14, -20)
      .toBuffer();
  }

  // Gaming grade (Variant A): vibrant, punchy
  return sharp(buf)
    .resize(W, H, { fit: 'cover', position: 'entropy' })
    .sharpen({ sigma: 0.6, m1: 0.4, m2: 2.8 })
    .modulate({ brightness: 1.04, saturation: 1.38 })
    .linear(1.06, -6)
    .toBuffer();
}

// ── Layout A: "Gaming Pro" (current design, preserved) ────────────────────────

function svgLayoutA(p: {
  headline: string; subheadline: string; category: string;
  channelName: string; W: number; H: number; fontBase64: string | null;
}): string {
  const { headline, subheadline, category, channelName, W, H, fontBase64 } = p;
  const isVertical = H > W;
  const { primary, glow: glowColor } = accentTheme(category);

  const safeHead = sanitizeSvg(headline.toUpperCase());
  const safeSub  = sanitizeSvg(subheadline || '');
  const safeCh   = sanitizeSvg((channelName || 'GLENVEX').toUpperCase());
  const safeCat  = sanitizeSvg(category || '');

  const headLines = splitHeadline(safeHead, isVertical ? 12 : 18);
  const wordCount = headline.trim().split(/\s+/).length;
  const baseDivisor = isVertical ? (wordCount >= 4 ? 8.5 : 6.5) : (wordCount >= 4 ? 11.5 : 9);
  const hSize = Math.round(W / baseDivisor);
  const sSize = Math.round(W / (isVertical ? 22 : 28));
  const chSize = Math.round(W / (isVertical ? 32 : 42));
  const badgeSize = Math.round(W / (isVertical ? 28 : 36));
  const hStroke = Math.max(5, Math.round(hSize / 7));
  const sStroke = Math.max(2, Math.round(sSize / 10));

  const accentBarH = Math.max(8, Math.round(H * 0.013));
  const leftBarW   = Math.max(10, Math.round(W * 0.012));
  const lineH      = headLines.length * (hSize * 1.1);
  const textBottom = H - accentBarH - (isVertical ? 60 : 44);
  const subY       = textBottom;
  const headBottomY = subheadline ? textBottom - sSize * 1.6 - 8 : textBottom;
  const headTopY   = headBottomY - lineH;
  const gradStart  = Math.max(0, Math.round(headTopY - hSize * 1.2));

  const fontDecl = fontBase64
    ? `@font-face { font-family: 'BebasNeue'; src: url('data:font/truetype;base64,${fontBase64}'); }`
    : '';
  const headFont = fontBase64 ? 'BebasNeue' : "Impact, 'Arial Black', sans-serif";
  const bodyFont = "'Liberation Sans', 'DejaVu Sans', Arial, sans-serif";

  const lineSpacing = hSize * 1.12;
  const headTspans = headLines.map((line, i) =>
    `<tspan x="${leftBarW + W * 0.06}" dy="${i === 0 ? 0 : lineSpacing}">${line}</tspan>`
  ).join('');

  const badgePad = 12;
  const badgeW = safeCat ? Math.max(60, safeCat.length * badgeSize * 0.62 + badgePad * 2) : 0;
  const badgeH = safeCat ? badgeSize + 14 : 0;

  return `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}">
  <defs>
    <style>${fontDecl}</style>
    <linearGradient id="grad-bot" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%"   stop-color="black" stop-opacity="0"/>
      <stop offset="30%"  stop-color="black" stop-opacity="0.08"/>
      <stop offset="65%"  stop-color="black" stop-opacity="0.58"/>
      <stop offset="85%"  stop-color="black" stop-opacity="0.88"/>
      <stop offset="100%" stop-color="black" stop-opacity="0.97"/>
    </linearGradient>
    <linearGradient id="grad-top" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%"  stop-color="black" stop-opacity="0.45"/>
      <stop offset="18%" stop-color="black" stop-opacity="0"/>
    </linearGradient>
    <linearGradient id="grad-left" x1="0" y1="0" x2="1" y2="0">
      <stop offset="0%"   stop-color="black" stop-opacity="0.6"/>
      <stop offset="20%"  stop-color="black" stop-opacity="0.1"/>
      <stop offset="100%" stop-color="black" stop-opacity="0"/>
    </linearGradient>
    <filter id="glow-h" x="-15%" y="-30%" width="130%" height="160%">
      <feGaussianBlur in="SourceAlpha" stdDeviation="10" result="blur"/>
      <feFlood flood-color="${glowColor}" flood-opacity="0.85" result="color"/>
      <feComposite in="color" in2="blur" operator="in" result="shadow"/>
      <feMerge><feMergeNode in="shadow"/><feMergeNode in="SourceGraphic"/></feMerge>
    </filter>
    <filter id="drop">
      <feDropShadow dx="0" dy="2" stdDeviation="4" flood-color="black" flood-opacity="0.9"/>
    </filter>
  </defs>
  <rect x="0" y="${gradStart}" width="${W}" height="${H - gradStart}" fill="url(#grad-bot)"/>
  <rect x="0" y="0" width="${W}" height="${Math.round(H * 0.22)}" fill="url(#grad-top)"/>
  <rect x="0" y="0" width="${Math.round(W * 0.22)}" height="${H}" fill="url(#grad-left)"/>
  <rect x="0" y="0" width="${leftBarW}" height="${H}" fill="${primary}"/>
  <rect x="0" y="${H - accentBarH}" width="${W}" height="${accentBarH}" fill="${primary}" opacity="0.95"/>
  ${safeCat ? `
  <rect x="${leftBarW + 16}" y="18" width="${badgeW}" height="${badgeH}" rx="5"
    fill="${primary}" opacity="0.92"/>
  <text x="${leftBarW + 16 + badgePad}" y="${18 + badgeH * 0.72}"
    font-family="${headFont}, sans-serif" font-weight="900" font-size="${badgeSize}px"
    fill="black" letter-spacing="1">${safeCat}</text>` : ''}
  <text x="${W - leftBarW - 18}" y="${badgeH + 26}" text-anchor="end"
    font-family="${headFont}, sans-serif" font-weight="900" font-size="${chSize}px"
    fill="${primary}" stroke="black" stroke-width="2" paint-order="stroke fill"
    filter="url(#drop)">${safeCh}</text>
  <text x="${leftBarW + W * 0.06}" y="${headTopY + hSize}"
    dominant-baseline="text-before-edge"
    font-family="${headFont}, sans-serif" font-weight="900" font-size="${hSize}px"
    fill="${primary}" stroke="black" stroke-width="${hStroke}" stroke-linejoin="round"
    paint-order="stroke fill" filter="url(#glow-h)" letter-spacing="2">${headTspans}</text>
  ${safeSub ? `<text x="${leftBarW + W * 0.06}" y="${subY}"
    dominant-baseline="text-before-edge"
    font-family="${bodyFont}" font-weight="bold" font-size="${sSize}px"
    fill="white" stroke="black" stroke-width="${sStroke}" stroke-linejoin="round"
    paint-order="stroke fill" filter="url(#drop)">${safeSub}</text>` : ''}
</svg>`;
}

// ── Layout B: "Cinema" (letterbox + centered text) ────────────────────────────

function svgLayoutB(p: {
  headline: string; subheadline: string; category: string;
  channelName: string; W: number; H: number; fontBase64: string | null;
}): string {
  const { headline, subheadline, category, channelName, W, H, fontBase64 } = p;
  const isVertical = H > W;
  const { primary } = accentTheme(category);

  const safeHead = sanitizeSvg(headline.toUpperCase());
  const safeSub  = sanitizeSvg(subheadline || '');
  const safeCh   = sanitizeSvg((channelName || 'GLENVEX').toUpperCase());
  const safeCat  = sanitizeSvg(category || '');

  const lbTop = Math.round(H * (isVertical ? 0.08 : 0.12));
  const lbBot = Math.round(H * (isVertical ? 0.06 : 0.08));

  const headLines = splitHeadline(safeHead, isVertical ? 10 : 16);
  const wordCount = headline.trim().split(/\s+/).length;
  const baseDivisor = isVertical ? (wordCount >= 4 ? 7.5 : 5.8) : (wordCount >= 4 ? 10 : 8);
  const hSize = Math.round(W / baseDivisor);
  const sSize = Math.round(W / (isVertical ? 20 : 26));
  const chSize = Math.round(W / (isVertical ? 30 : 38));
  const catSize = Math.round(W / (isVertical ? 32 : 40));
  const hStroke = Math.max(5, Math.round(hSize / 8));
  const sStroke = Math.max(2, Math.round(sSize / 12));

  const lineSpacing = hSize * 1.1;
  const totalHeadH = headLines.length * lineSpacing + (safeSub ? sSize * 1.7 : 0);
  // Text bottom is flush above the bottom letterbox with a small margin
  const textBottomY = H - lbBot - 18;
  const headAreaY = textBottomY - totalHeadH;

  const gradStartY = Math.round(H * 0.45);

  const fontDecl = fontBase64
    ? `@font-face { font-family: 'BebasNeue'; src: url('data:font/truetype;base64,${fontBase64}'); }`
    : '';
  const headFont = fontBase64 ? 'BebasNeue' : "Impact, 'Arial Black', sans-serif";
  const bodyFont = "'Liberation Sans', 'DejaVu Sans', Arial, sans-serif";

  const headTspans = headLines.map((line, i) =>
    `<tspan x="${W / 2}" dy="${i === 0 ? 0 : lineSpacing}">${line}</tspan>`
  ).join('');

  return `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}">
  <defs>
    <style>${fontDecl}</style>
    <radialGradient id="vig-b" cx="50%" cy="50%" r="70%" gradientUnits="objectBoundingBox">
      <stop offset="0%"   stop-color="black" stop-opacity="0"/>
      <stop offset="60%"  stop-color="black" stop-opacity="0.2"/>
      <stop offset="100%" stop-color="black" stop-opacity="0.75"/>
    </radialGradient>
    <linearGradient id="grad-b-bot" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%"   stop-color="black" stop-opacity="0"/>
      <stop offset="50%"  stop-color="black" stop-opacity="0.55"/>
      <stop offset="100%" stop-color="black" stop-opacity="0.95"/>
    </linearGradient>
    <filter id="glow-b" x="-20%" y="-35%" width="140%" height="170%">
      <feGaussianBlur in="SourceAlpha" stdDeviation="12" result="blur"/>
      <feFlood flood-color="${primary}" flood-opacity="0.7" result="color"/>
      <feComposite in="color" in2="blur" operator="in" result="shadow"/>
      <feMerge><feMergeNode in="shadow"/><feMergeNode in="SourceGraphic"/></feMerge>
    </filter>
    <filter id="drop-b">
      <feDropShadow dx="0" dy="2" stdDeviation="4" flood-color="black" flood-opacity="0.95"/>
    </filter>
  </defs>
  <rect x="0" y="0" width="${W}" height="${H}" fill="url(#vig-b)"/>
  <rect x="0" y="${gradStartY}" width="${W}" height="${H - gradStartY}" fill="url(#grad-b-bot)"/>
  <rect x="0" y="0" width="${W}" height="${lbTop}" fill="black"/>
  <rect x="0" y="${H - lbBot}" width="${W}" height="${lbBot}" fill="black"/>
  <rect x="0" y="${lbTop - 2}" width="${W}" height="2" fill="${primary}" opacity="0.85"/>
  <rect x="0" y="${H - lbBot}" width="${W}" height="2" fill="${primary}" opacity="0.85"/>
  <text x="${W / 2}" y="${lbTop * 0.65}"
    text-anchor="middle" dominant-baseline="middle"
    font-family="${headFont}, sans-serif" font-weight="900" font-size="${chSize}px"
    fill="white" stroke="black" stroke-width="2" paint-order="stroke fill"
    filter="url(#drop-b)" letter-spacing="4">${safeCh}</text>
  ${safeCat ? `
  <text x="20" y="${H - lbBot / 2}"
    dominant-baseline="middle"
    font-family="${headFont}, sans-serif" font-weight="900" font-size="${catSize}px"
    fill="${primary}" filter="url(#drop-b)" letter-spacing="1">${safeCat}</text>` : ''}
  <text x="${W / 2}" y="${headAreaY}"
    text-anchor="middle" dominant-baseline="text-before-edge"
    font-family="${headFont}, sans-serif" font-weight="900" font-size="${hSize}px"
    fill="white" stroke="black" stroke-width="${hStroke}" stroke-linejoin="round"
    paint-order="stroke fill" filter="url(#glow-b)" letter-spacing="2">${headTspans}</text>
  ${safeSub ? `<text x="${W / 2}" y="${headAreaY + headLines.length * lineSpacing + 8}"
    text-anchor="middle" dominant-baseline="text-before-edge"
    font-family="${bodyFont}" font-weight="bold" font-size="${sSize}px"
    fill="white" stroke="black" stroke-width="${sStroke}" stroke-linejoin="round"
    paint-order="stroke fill" filter="url(#drop-b)">${safeSub}</text>` : ''}
</svg>`;
}

// ── Layout C: "Impact Block" (solid color panel at bottom) ───────────────────

function svgLayoutC(p: {
  headline: string; subheadline: string; category: string;
  channelName: string; W: number; H: number; fontBase64: string | null;
}): string {
  const { headline, subheadline, category, channelName, W, H, fontBase64 } = p;
  const isVertical = H > W;
  const { primary, secondary } = accentTheme(category);

  const safeHead = sanitizeSvg(headline.toUpperCase());
  const safeSub  = sanitizeSvg(subheadline || '');
  const safeCh   = sanitizeSvg((channelName || 'GLENVEX').toUpperCase());
  const safeCat  = sanitizeSvg(category || '');

  const panelY = Math.round(H * (isVertical ? 0.70 : 0.68));
  const panelH = H - panelY;
  const padL = Math.round(W * 0.04);

  const headLines = splitHeadline(safeHead, isVertical ? 11 : 16);
  const wordCount = headline.trim().split(/\s+/).length;
  const baseDivisor = isVertical ? (wordCount >= 4 ? 8 : 6.2) : (wordCount >= 4 ? 10.5 : 8.5);
  const hSize = Math.round(W / baseDivisor);
  const sSize = Math.round(W / (isVertical ? 24 : 32));
  const chSize = Math.round(W / (isVertical ? 34 : 44));
  const badgeSize = Math.round(W / (isVertical ? 30 : 38));

  const lineSpacing = hSize * 1.1;
  // Top padding inside panel
  const headY = panelY + Math.round(panelH * 0.18);

  const fontDecl = fontBase64
    ? `@font-face { font-family: 'BebasNeue'; src: url('data:font/truetype;base64,${fontBase64}'); }`
    : '';
  const headFont = fontBase64 ? 'BebasNeue' : "Impact, 'Arial Black', sans-serif";
  const bodyFont = "'Liberation Sans', 'DejaVu Sans', Arial, sans-serif";

  const headTspans = headLines.map((line, i) =>
    `<tspan x="${padL}" dy="${i === 0 ? 0 : lineSpacing}">${line}</tspan>`
  ).join('');

  const badgePad = 10;
  const badgeW = safeCat ? Math.max(60, safeCat.length * badgeSize * 0.62 + badgePad * 2) : 0;
  const badgeH = safeCat ? badgeSize + 12 : 0;
  const badgeX = W - badgeW - 16;

  return `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}">
  <defs>
    <style>${fontDecl}</style>
    <radialGradient id="vig-c" cx="50%" cy="50%" r="65%" gradientUnits="objectBoundingBox">
      <stop offset="0%"   stop-color="black" stop-opacity="0"/>
      <stop offset="50%"  stop-color="black" stop-opacity="0.2"/>
      <stop offset="100%" stop-color="black" stop-opacity="0.82"/>
    </radialGradient>
    <linearGradient id="grad-c-top" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%"  stop-color="black" stop-opacity="0.65"/>
      <stop offset="25%" stop-color="black" stop-opacity="0"/>
    </linearGradient>
    <filter id="drop-c">
      <feDropShadow dx="0" dy="2" stdDeviation="3" flood-color="black" flood-opacity="1"/>
    </filter>
  </defs>
  <rect x="0" y="0" width="${W}" height="${H}" fill="url(#vig-c)"/>
  <rect x="0" y="0" width="${W}" height="${Math.round(H * 0.28)}" fill="url(#grad-c-top)"/>
  <rect x="0" y="${panelY}" width="${W}" height="${panelH}" fill="${primary}" opacity="0.93"/>
  <rect x="0" y="${panelY}" width="${W}" height="3" fill="white" opacity="0.55"/>
  <rect x="0" y="${panelY + 7}" width="${W}" height="1" fill="white" opacity="0.2"/>
  <text x="${padL}" y="${headY}"
    dominant-baseline="text-before-edge"
    font-family="${headFont}, sans-serif" font-weight="900" font-size="${hSize}px"
    fill="white" letter-spacing="2">${headTspans}</text>
  ${safeSub ? `<text x="${padL}" y="${headY + headLines.length * lineSpacing + 8}"
    dominant-baseline="text-before-edge"
    font-family="${bodyFont}" font-weight="bold" font-size="${sSize}px"
    fill="white" opacity="0.88">${safeSub}</text>` : ''}
  <text x="16" y="${chSize + 14}"
    font-family="${headFont}, sans-serif" font-weight="900" font-size="${chSize}px"
    fill="white" filter="url(#drop-c)" letter-spacing="2">${safeCh}</text>
  ${safeCat ? `
  <rect x="${badgeX}" y="12" width="${badgeW}" height="${badgeH}" rx="5"
    fill="${secondary}" opacity="0.95"/>
  <text x="${badgeX + badgePad}" y="${12 + badgeH * 0.72}"
    font-family="${headFont}, sans-serif" font-weight="900" font-size="${badgeSize}px"
    fill="white" letter-spacing="1">${safeCat}</text>` : ''}
</svg>`;
}

// ── Composite One Variant ─────────────────────────────────────────────────────

async function buildOneVariant(
  videoUrl: string,
  frameT: number,
  copy: { headline: string; subheadline: string },
  category: string,
  channelName: string,
  layout: 'a' | 'b' | 'c',
  W: number,
  H: number,
  fontBase64: string | null,
  label: string
): Promise<Buffer | null> {
  log(`COMPOSITING_${label}`, `${W}x${H} layout=${layout} t=${frameT.toFixed(1)}s`);
  const hiBuf = await spawnFrame(videoUrl, frameT, W, H, 16_000);
  if (!hiBuf) { log(`FRAME_FETCH_FAILED_${label}`); return null; }
  try {
    const sharp = require('sharp');
    const grade: ColorGrade = layout === 'b' ? 'cinematic' : layout === 'c' ? 'drama' : 'gaming';
    const enhanced = await applyColorGrade(hiBuf, W, H, grade);
    const svgBuilders = { a: svgLayoutA, b: svgLayoutB, c: svgLayoutC };
    const svg = svgBuilders[layout]({ headline: copy.headline, subheadline: copy.subheadline, category, channelName, W, H, fontBase64 });
    return await sharp(enhanced)
      .composite([{ input: Buffer.from(svg), top: 0, left: 0 }])
      .png({ compressionLevel: 7 })
      .toBuffer();
  } catch (e: any) {
    log(`COMPOSITE_FAILED_${label}`, e.message?.slice(0, 200));
    return null;
  }
}

// ── Quality Score ─────────────────────────────────────────────────────────────

function computeQualityScore(opts: {
  extractedFrames: number;
  visionUsed: boolean;
  headline: string;
  hasYoutube: boolean;
  hasTiktok: boolean;
  bestFramePct: number;
  fontAvailable: boolean;
}): number {
  let score = 0;
  score += Math.min(25, Math.round((opts.extractedFrames / FRAME_COUNT) * 25));
  score += opts.visionUsed ? 20 : 8;
  const words = opts.headline.trim().split(/\s+/).length;
  score += words >= 2 && words <= 4 ? 25 : words === 5 ? 15 : 5;
  score += opts.hasYoutube && opts.hasTiktok ? 20 : opts.hasYoutube || opts.hasTiktok ? 10 : 0;
  const pct = opts.bestFramePct;
  score += pct >= 15 && pct <= 85 ? 10 : 5;
  return Math.min(100, Math.round(score));
}

// ── Storage Upload ────────────────────────────────────────────────────────────

async function uploadPng(sb: any, buf: Buffer, sti: string): Promise<string | null> {
  try {
    const { error } = await sb.storage.from(STORAGE_BUCKET).upload(sti, buf, {
      contentType: 'image/png',
      upsert: true,
    });
    if (error) { log('UPLOAD_ERROR', JSON.stringify(error)); return null; }
    const { data } = sb.storage.from(STORAGE_BUCKET).getPublicUrl(sti);
    return (data as any)?.publicUrl ?? null;
  } catch (e: any) {
    log('UPLOAD_EXCEPTION', e.message?.slice(0, 200));
    return null;
  }
}

// ── Channel Name ──────────────────────────────────────────────────────────────

async function hentKanalNavn(sb: any, vodId: string): Promise<string> {
  try {
    const { data } = await sb.from('content_vods')
      .select('twitch_channel_name,title')
      .eq('id', vodId)
      .single();
    return data?.twitch_channel_name ?? '';
  } catch { return ''; }
}

// ── Main Builder ──────────────────────────────────────────────────────────────

export async function buildThumbnailV2(highlightId: string): Promise<void> {
  const sbUrl  = process.env.SUPABASE_URL;
  const sbKey  = process.env.SUPABASE_SERVICE_ROLE_KEY;
  const apiKey = process.env.OPENAI_API_KEY;
  if (!sbUrl || !sbKey || !apiKey) {
    log('ERROR', 'Mangler SUPABASE_URL / SERVICE_ROLE_KEY / OPENAI_API_KEY');
    return;
  }

  const sb     = createClient(sbUrl, sbKey, { realtime: { transport: require('ws') } });
  const client = new OpenAI({ apiKey });

  await sb.from('content_highlights').update({
    thumbnail_status: 'GENERATING',
    thumbnail_error:  null,
  }).eq('id', highlightId).in('thumbnail_status', ['PENDING', 'GENERATING']);
  await sb.from('content_highlights').update({ thumbnail_started_at: new Date().toISOString() }).eq('id', highlightId);

  log('JOB_CLAIMED', highlightId);
  logSystemEvent({ source: 'thumbnail', event_type: 'THUMBNAIL_JOB_CLAIMED', title: `Thumbnail V3 claim: ${highlightId.slice(0, 8)}`, severity: 'info', metadata: { highlight_id: highlightId } });

  try {
    // ── Fetch data ─────────────────────────────────────────────────────────
    const { data: h, error: hErr } = await sb.from('content_highlights')
      .select('id,vod_id,title,category,begrunnelse,clip_url,vertical_clip_url,clip_status')
      .eq('id', highlightId)
      .single();

    if (hErr || !h) throw new Error('Highlight ikke funnet');
    if (h.clip_status !== 'CLIPPED') throw new Error(`clip_status = ${h.clip_status}`);

    const videoUrl = h.clip_url ?? h.vertical_clip_url;
    if (!videoUrl) throw new Error('Ingen clip_url eller vertical_clip_url');

    const [vodRes, copiesRes] = await Promise.all([
      sb.from('content_vods').select('id,title,category').eq('id', h.vod_id).single(),
      sb.from('content_copy').select('platform,tittel,caption').eq('highlight_id', highlightId),
    ]);
    const vod    = vodRes.data;
    const copies = copiesRes.data ?? [];
    const game   = vod?.category ?? vod?.title ?? 'video game';
    const channel = await hentKanalNavn(sb, h.vod_id);

    const fontBase64 = await getFontBase64();
    log(fontBase64 ? 'FONT_READY' : 'FONT_FALLBACK', fontBase64 ? 'Bebas Neue OK' : 'system-font');

    // ── Frame extraction (20 frames) ────────────────────────────────────────
    log('FRAME_EXTRACTION_STARTED');
    logSystemEvent({ source: 'thumbnail', event_type: 'FRAME_EXTRACTION_STARTED', title: `Ekstraher ${FRAME_COUNT} frames: "${(h.title ?? '').slice(0, 60)}"`, severity: 'info', metadata: { highlight_id: highlightId, frame_count: FRAME_COUNT } });

    const duration  = await getClipDuration(videoUrl);
    const rawFrames = await extractCandidateFrames(videoUrl, duration);
    log('FRAMES_EXTRACTED', `${rawFrames.length}/${FRAME_COUNT} OK`);
    logSystemEvent({ source: 'thumbnail', event_type: 'FRAME_EXTRACTION_DONE', title: `${rawFrames.length}/${FRAME_COUNT} frames OK`, severity: 'info', metadata: { highlight_id: highlightId, frames: rawFrames.length } });

    if (rawFrames.length === 0) throw new Error('Ingen frames kunne ekstraheres');

    // ── Score + rank ────────────────────────────────────────────────────────
    const scored = rawFrames
      .map(f => ({ ...f, score: scoreFrame(f) }))
      .sort((a, b) => b.score - a.score)
      .slice(0, TOP_CANDIDATES);

    // ── CTR Vision selection ────────────────────────────────────────────────
    let visionUsed = false;
    let ctrResult: CtrResult = { selectedIdx: 0, ctrScore: 50, reason: '' };

    logSystemEvent({ source: 'thumbnail', event_type: 'THUMBNAIL_FRAME_ANALYSIS_STARTED', title: `GPT Vision CTR-analyse (${scored.length} kandidater)`, severity: 'info', metadata: { highlight_id: highlightId, candidates: scored.length } });

    if (scored.length > 1) {
      ctrResult  = await selectBestFrameWithCtr(client, scored, h.category, game);
      visionUsed = true;
    }

    logSystemEvent({
      source: 'thumbnail', event_type: 'THUMBNAIL_FRAME_SELECTED',
      title: `Frame valgt: t=${scored[ctrResult.selectedIdx]?.t?.toFixed(1) ?? '?'}s CTR=${ctrResult.ctrScore}/100`,
      severity: 'info',
      metadata: { highlight_id: highlightId, vision_used: visionUsed, frame_t: scored[ctrResult.selectedIdx]?.t, ctr_score: ctrResult.ctrScore, ctr_reason: ctrResult.reason },
    });

    const orderedCandidates = [
      scored[ctrResult.selectedIdx],
      ...scored.filter((_, i) => i !== ctrResult.selectedIdx),
    ];

    // ── Copy generation ─────────────────────────────────────────────────────
    const copy = await generateCopy(client, h, vod, copies, orderedCandidates[0].buf.toString('base64'));
    log('COPY_GENERATED', `"${copy.headline}" / "${copy.subheadline}"`);

    // ── Variant A: retry loop for quality ───────────────────────────────────
    log('IMAGE_BUILD_STARTED', 'Varianter A/B/C');
    logSystemEvent({ source: 'thumbnail', event_type: 'THUMBNAIL_RENDER_STARTED', title: `Kompositter: "${copy.headline}"`, severity: 'info', metadata: { highlight_id: highlightId, headline: copy.headline, font: fontBase64 ? 'BebasNeue' : 'system' } });

    let bestYtBuf: Buffer | null = null;
    let bestTtBuf: Buffer | null = null;
    let usedFrameT = orderedCandidates[0].t;
    let bestScore  = 0;
    const ttSource = h.vertical_clip_url ?? h.clip_url;
    const attemptsToTry = Math.min(orderedCandidates.length, MAX_RETRIES + 1);

    for (let attempt = 0; attempt < attemptsToTry; attempt++) {
      const candidate = orderedCandidates[attempt];
      const [ytBuf, ttBuf] = await Promise.all([
        buildOneVariant(h.clip_url, candidate.t, copy, h.category, channel, 'a', YT_W, YT_H, fontBase64, 'YT_A'),
        buildOneVariant(ttSource,   candidate.t, copy, h.category, channel, 'a', TT_W, TT_H, fontBase64, 'TT_A'),
      ]);
      const score = computeQualityScore({
        extractedFrames: rawFrames.length,
        visionUsed,
        headline: copy.headline,
        hasYoutube: !!ytBuf,
        hasTiktok:  !!ttBuf,
        bestFramePct: candidate.pct,
        fontAvailable: !!fontBase64,
      });
      log(`ATTEMPT_${attempt + 1}_SCORE`, `${score} (t=${candidate.t.toFixed(1)}s)`);
      if (score > bestScore || (!bestYtBuf && !bestTtBuf)) {
        bestYtBuf  = ytBuf;
        bestTtBuf  = ttBuf;
        bestScore  = score;
        usedFrameT = candidate.t;
      }
      if (score >= QUALITY_THRESHOLD) break;
    }

    // ── Variants B and C from the winning frame ─────────────────────────────
    // Use resolved videoUrl (clip_url ?? vertical_clip_url) so B/C work even
    // when a highlight only has a vertical clip.
    const [ytBufB, ytBufC] = await Promise.all([
      buildOneVariant(videoUrl, usedFrameT, copy, h.category, channel, 'b', YT_W, YT_H, fontBase64, 'YT_B'),
      buildOneVariant(videoUrl, usedFrameT, copy, h.category, channel, 'c', YT_W, YT_H, fontBase64, 'YT_C'),
    ]);

    log('IMAGE_BUILD_DONE', `score=${bestScore} A=${!!bestYtBuf} B=${!!ytBufB} C=${!!ytBufC}`);
    logSystemEvent({
      source: 'thumbnail', event_type: 'THUMBNAIL_VARIANTS_GENERATED',
      title: `Varianter A/B/C generert (score: ${bestScore}/100)`,
      severity: 'info',
      metadata: { highlight_id: highlightId, score: bestScore, has_a: !!bestYtBuf, has_b: !!ytBufB, has_c: !!ytBufC },
    });

    if (!bestYtBuf && !bestTtBuf) throw new Error('Compositing feilet for alle forsøk');

    // ── Upload – sequential with hard evidence per step ─────────────────────
    const wsId   = process.env.WORKSPACE_ID ?? '(ikke satt)';
    const baseSti = `content-factory/thumbnails/${h.vod_id}/${highlightId}`;
    log('UPLOAD_CTX', `bucket=${STORAGE_BUCKET} vod=${h.vod_id} highlight=${highlightId} ws=${wsId}`);
    logSystemEvent({ source: 'thumbnail', event_type: 'SUPABASE_UPLOAD_STARTED', title: 'Laster opp thumbnails (A+B+C)', severity: 'info', metadata: { highlight_id: highlightId, bucket: STORAGE_BUCKET } });

    async function uploadAndLog(buf: Buffer | null, sti: string, label: string): Promise<string | null> {
      if (!buf) { log(`UPLOAD_${label}_SKIP`, 'buffer null'); return null; }
      log(`UPLOAD_${label}_START`, `size=${buf.length} path=${sti}`);
      const url = await uploadPng(sb, buf, sti);
      log(`UPLOAD_${label}_RESULT`, url
        ? `OK url=...${url.slice(-60)}`
        : `FAILED – ingen URL (sjekk UPLOAD_ERROR over)`
      );
      return url;
    }

    const ytUrl  = await uploadAndLog(bestYtBuf, `${baseSti}_youtube.png`,   'A');
    const ttUrl  = await uploadAndLog(bestTtBuf, `${baseSti}_tiktok.png`,    'TIKTOK');
    const ytUrlB = await uploadAndLog(ytBufB,    `${baseSti}_variant_b.png`, 'B');
    const ytUrlC = await uploadAndLog(ytBufC,    `${baseSti}_variant_c.png`, 'C');

    log('UPLOAD_SUMMARY', `A=${ytUrl ? 'OK' : 'NULL'} TT=${ttUrl ? 'OK' : 'NULL'} B=${ytUrlB ? 'OK' : 'NULL'} C=${ytUrlC ? 'OK' : 'NULL'}`);

    if (!ytUrl && !ttUrl) throw new Error('Opplasting til Supabase Storage feilet (begge null)');
    logSystemEvent({ source: 'thumbnail', event_type: 'SUPABASE_UPLOAD_DONE', title: 'Thumbnails lastet opp', severity: 'info', metadata: { highlight_id: highlightId, yt_url: ytUrl, tt_url: ttUrl, b_url: ytUrlB, c_url: ytUrlC } });

    // ── Primary DB update ───────────────────────────────────────────────────
    log('DB_UPDATE_START', `highlight_id=${highlightId} status=DONE yt=${ytUrl ? 'OK' : 'NULL'}`);
    const { data: doneRows, error: doneErr } = await sb.from('content_highlights').update({
      thumbnail_status:       'DONE',
      thumbnail_youtube_url:  ytUrl  ?? null,
      thumbnail_tiktok_url:   ttUrl  ?? null,
      thumbnail_headline:     copy.headline,
      thumbnail_subheadline:  copy.subheadline || null,
      thumbnail_generated_at: new Date().toISOString(),
      thumbnail_error:        null,
      thumbnail_prompt:       null,
    }).eq('id', highlightId).select('id,thumbnail_status,thumbnail_youtube_url');

    if (doneErr) {
      log('DB_UPDATE_FAILED', `err=${doneErr.message} code=${(doneErr as any).code}`);
      throw new Error('DB DONE-oppdatering feilet: ' + doneErr.message);
    }
    log('DB_UPDATE_SUCCESS', `affected=${doneRows?.length ?? 0} status=${doneRows?.[0]?.thumbnail_status ?? 'ukjent'} yt=${doneRows?.[0]?.thumbnail_youtube_url ? 'SET' : 'NULL'}`);

    if ((doneRows?.length ?? 0) === 0) {
      log('DB_UPDATE_WARN', `0 rader oppdatert – highlight_id=${highlightId} finnes kanskje ikke i Supabase`);
    }

    await sb.from('content_highlights').update({
      thumbnail_source_frame:  usedFrameT,
      thumbnail_quality_score: bestScore,
    }).eq('id', highlightId);

    // ── Variant B/C + CTR columns (requires thumbnail-v3-migration.sql) ─────
    try {
      const { error: varErr } = await sb.from('content_highlights').update({
        thumbnail_variant_b_url: ytUrlB ?? null,
        thumbnail_variant_c_url: ytUrlC ?? null,
        thumbnail_ctr_score:     ctrResult.ctrScore,
        thumbnail_ctr_reason:    ctrResult.reason || null,
      }).eq('id', highlightId);
      if (varErr) {
        log('VARIANT_COLS_SKIP', varErr.message?.slice(0, 120));
      } else {
        log('VARIANT_COLS_OK', `B=${ytUrlB ? 'SET' : 'NULL'} C=${ytUrlC ? 'SET' : 'NULL'} ctr=${ctrResult.ctrScore}`);
      }
    } catch (variantErr: any) {
      log('VARIANT_COLS_SKIP', variantErr.message?.slice(0, 120));
    }

    // ── DB read-back: hard proof of what Supabase actually stored ───────────
    try {
      const { data: rbRow, error: rbErr } = await sb.from('content_highlights')
        .select('id,thumbnail_status,thumbnail_youtube_url,thumbnail_tiktok_url,thumbnail_variant_b_url,thumbnail_variant_c_url,thumbnail_ctr_score')
        .eq('id', highlightId)
        .single();
      log('DB_READBACK', rbErr
        ? `READ_ERROR: ${rbErr.message?.slice(0, 80)}`
        : `status=${rbRow?.thumbnail_status} yt=${rbRow?.thumbnail_youtube_url ? 'SET' : 'NULL'} tt=${rbRow?.thumbnail_tiktok_url ? 'SET' : 'NULL'} b=${rbRow?.thumbnail_variant_b_url ? 'SET' : 'NULL'} c=${rbRow?.thumbnail_variant_c_url ? 'SET' : 'NULL'} ctr=${rbRow?.thumbnail_ctr_score ?? 'NULL'}`
      );
    } catch {}

    log('THUMBNAIL_V3_DONE', `score=${bestScore} frame=${usedFrameT.toFixed(1)}s CTR=${ctrResult.ctrScore}`);
    logSystemEvent({
      source: 'thumbnail', event_type: 'THUMBNAIL_COMPLETED',
      title: `Thumbnail FERDIG – score ${bestScore}/100 CTR ${ctrResult.ctrScore}/100`,
      description: `"${(h.title ?? '').slice(0, 80)}"`,
      severity: 'info',
      metadata: { highlight_id: highlightId, score: bestScore, ctr_score: ctrResult.ctrScore, ctr_reason: ctrResult.reason, frame_t: usedFrameT, yt_url: ytUrl, tt_url: ttUrl, b_url: ytUrlB, c_url: ytUrlC },
    });

  } catch (err: any) {
    const msg = (err.message ?? 'Ukjent feil').slice(0, 300);
    log('FAILED', msg);
    logSystemEvent({ source: 'thumbnail', event_type: 'THUMBNAIL_FAILED', title: 'Thumbnail FEILET', description: msg, severity: 'error', metadata: { highlight_id: highlightId, error: msg } });
    try {
      await sb.from('content_highlights').update({
        thumbnail_status: 'FAILED',
        thumbnail_error:  msg,
      }).eq('id', highlightId);
    } catch {}
  }
}
